import Foundation

// MARK: - Story Chain cards
//
// Bundled and offline. Openers are the first line of a silly story, read
// out by the phone's holder; every player then adds one sentence out loud.
// Twists turn up every few turns and bend the next sentence. Everything
// here is family friendly.

enum StoryChainDeck {

    static let openers: [String] = [
        "The talking fridge had one final request...",
        "Grandma's goldfish had been planning the bank robbery for years...",
        "Nobody expected the school bus to start flying on a Tuesday...",
        "The moment the pizza delivery driver whispered the password, everything changed...",
        "Deep in the sock drawer, a tiny kingdom was preparing for war...",
        "The dog finally learned to talk, and the first thing he said was...",
        "On the night of the big talent show, the toaster went missing...",
        "The wizard woke up to find his magic wand had been swapped for a carrot...",
        "Every time Uncle Kevin sneezed, it started raining spaghetti...",
        "The pirate ship was lost, mostly because the captain refused to ask for directions...",
        "Aliens landed in the back garden, but they only wanted to borrow a ladder...",
        "The haunted house was for sale, and the ghost was very fussy about buyers...",
        "My left shoe woke up this morning with a terrible secret...",
        "The museum's dinosaur skeleton was caught dancing after closing time...",
        "The world's worst superhero had exactly one power: perfectly toasting bread...",
        "A penguin walked into the library and asked for a book about deserts...",
        "Somewhere under the city, the pigeons were holding an emergency meeting...",
        "The robot butler had started taking very long lunch breaks...",
        "When the clock struck thirteen, the cat put on a tiny hat...",
        "The dragon was terrified of exactly one thing: birthday candles...",
        "Halfway up the mountain, the hikers met a goat selling sunglasses...",
        "The new teacher was definitely a vampire, and also very good at maths...",
        "The vending machine only gave out advice, and today's advice was very strange...",
        "Our neighbour built a rocket out of shopping trolleys...",
        "The snowman refused to melt until he got his revenge...",
        "The queen dropped the royal crown into a bowl of soup...",
        "At exactly noon, every mirror in town started telling bad jokes...",
        "The detective's only clue was a single soggy chip...",
        "The family car had developed strong opinions about music...",
        "The first cafe on the moon had just opened, and the coffee kept floating away...",
        "The garden gnomes had finally had enough...",
        "A mysterious parcel arrived, addressed to Whoever Is Brave Enough...",
        "The world's slowest snail had somehow entered the Olympics...",
        "The lighthouse keeper heard a knock on the door, in the middle of the sea, at midnight...",
        "The baby elephant escaped from the zoo and went straight to the hairdresser...",
        "Auntie Pam swore the cupcakes were not glowing on purpose...",
        "The submarine crew had only one rule: never wake the octopus...",
        "The time machine worked perfectly, except it only went back five minutes...",
        "The scarecrow was elected mayor by accident...",
        "Deep in the jungle, a parrot started repeating everyone's secrets...",
        "The knight's armour was three sizes too big, and the dragon had noticed...",
        "The school's lost property box had come to life...",
        "A sandwich fell out of the sky and landed on the mayor's head...",
        "The tooth fairy was running seriously low on coins...",
        "When the power went out, the house plants started whispering...",
        "The hotel lift had a button that nobody had ever dared to press...",
        "The cowboy's horse was much better at cards than the cowboy...",
        "The world's most famous chef had lost her sense of taste, and her favourite spoon...",
        "At the bottom of the swimming pool, someone had painted a door...",
        "Dad's new invention was supposed to fold the laundry...",
        "The ghost had been haunting the wrong house for three hundred years...",
        "Nobody knew why the bakery only opened at three in the morning...",
        "The astronaut's cat had secretly been flying the spaceship all along...",
        "Every sock in the house vanished on the same night...",
        "The village's giant vegetable contest was going well, until the pumpkin moved...",
        "The postman delivered a letter from the future...",
        "The traffic lights had started playing rock, paper, scissors...",
        "The prince was turned into a frog, and honestly, he preferred it...",
        "At the stroke of midnight, the board game started playing itself...",
        "The weather forecast said cloudy, with a chance of llamas...",
        "The world's grumpiest unicorn had a dentist appointment...",
        "Just as the wedding cake was cut, a trumpet sounded from inside it...",
    ]

    static let twists: [String] = [
        "Someone must sneeze",
        "Add a villain",
        "Rhyme your line",
        "Bring in a talking animal",
        "Something goes BOOM",
        "Say your line in a whisper",
        "Say your line like a robot",
        "Use the word banana",
        "Somebody falls in love",
        "Add a twist nobody saw coming",
        "It starts raining something strange",
        "Somebody loses their trousers",
        "Say it like a pirate",
        "Somebody has to sing",
        "Introduce a long-lost twin",
        "Move the story to outer space",
        "It was all a dream... or was it?",
        "Somebody gets a superpower",
        "Use three words that start with S",
        "End with: and then it got worse",
        "Add a secret door",
        "Your line must be a question",
        "Somebody gets stuck",
        "Bring back the very first character",
        "Add a very dramatic pause",
        "Say it in your poshest voice",
        "Someone cries happy tears",
        "Introduce a magical object",
        "The villain turns out to be nice",
        "Jump forward one hundred years",
        "Somebody has to dance",
        "Mention a sandwich",
        "Describe a terrible smell",
        "Start a chase scene",
        "Say your line in slow motion",
        "Somebody's phone rings at the worst moment",
    ]
}
