import Foundation

// MARK: - Bundled Travel Mode deck
//
// Family-friendly riddles and fun-fact quiz questions that work with no
// signal at all. Every line here is spoken aloud, so keep prompts short,
// punctuation simple, and answers easy to say. `accepts` lists the other
// ways people say the answer out loud (digits, synonyms, plurals are
// handled by TravelAnswerMatcher already).

enum TravelDeck {

    private static func riddle(_ prompt: String, _ answer: String, _ accepts: [String] = [],
                               hint: String, fact: String? = nil) -> TravelItem {
        TravelItem(kind: .riddle, prompt: prompt, answer: answer, accepts: accepts,
                   hint: hint, fact: fact)
    }

    private static func quiz(_ prompt: String, _ answer: String, _ accepts: [String] = [],
                             hint: String, fact: String? = nil) -> TravelItem {
        TravelItem(kind: .quiz, prompt: prompt, answer: answer, accepts: accepts,
                   hint: hint, fact: fact)
    }

    // MARK: Riddles

    static let riddles: [TravelItem] = [
        riddle("What has keys but can't open a single lock?", "a piano", ["keyboard"],
               hint: "It makes music."),
        riddle("What has to be broken before you can use it?", "an egg",
               hint: "You might have it for breakfast."),
        riddle("What gets wetter the more it dries?", "a towel",
               hint: "You grab it after a shower."),
        riddle("What has hands but can't clap?", "a clock", ["watch"],
               hint: "You check it when you're running late."),
        riddle("What has a neck but no head?", "a bottle",
               hint: "You drink from it."),
        riddle("What can you catch but never throw?", "a cold", ["flu"],
               hint: "Achoo!"),
        riddle("What goes up but never ever comes down?", "your age", ["age"],
               hint: "It happens on every birthday."),
        riddle("What has one eye but can't see?", "a needle",
               hint: "You use it for sewing."),
        riddle("What belongs to you, but other people use it way more than you do?",
               "your name", ["name"],
               hint: "People call you by it."),
        riddle("What gets bigger the more you take away from it?", "a hole",
               hint: "You dig it with a shovel."),
        riddle("I'm tall when I'm young and short when I'm old. What am I?", "a candle",
               hint: "You find me on birthday cakes."),
        riddle("What has lots of teeth but can't bite?", "a comb",
               hint: "You use it on your hair."),
        riddle("What can travel all around the world while staying in one corner?", "a stamp",
               hint: "It goes on an envelope."),
        riddle("What has a head and a tail but no body?", "a coin",
               hint: "Flip it to decide who gets the window seat."),
        riddle("What has four legs but can't walk?", "a table", ["chair"],
               hint: "You eat dinner at it."),
        riddle("What runs but never walks, and has a mouth but never talks?", "a river", ["stream"],
               hint: "It flows all the way to the sea."),
        riddle("What is full of holes but still holds water?", "a sponge",
               hint: "You wash the dishes with it."),
        riddle("Some months have 31 days, some have 30. How many have 28?", "all of them",
               ["all", "every month", "all twelve", "twelve", "12"],
               hint: "Think about every single month.",
               fact: "Every month has at least 28 days!"),
        riddle("What can fill a room but takes up no space at all?", "light", ["darkness", "air"],
               hint: "Flip a switch."),
        riddle("What do you call a bear with no teeth?", "a gummy bear", ["gummy"],
               hint: "It's a chewy sweet."),
        riddle("What has words but never speaks?", "a book",
               hint: "You read it."),
        riddle("What kind of room has no doors and no windows?", "a mushroom",
               hint: "It grows in the forest."),
        riddle("Which building has the most stories?", "a library",
               hint: "It's full of books.",
               fact: "Get it? Stories!"),
        riddle("What goes through cities and fields but never moves?", "a road",
               ["highway", "street"],
               hint: "You're on one right now!"),
        riddle("What has four wheels and flies?", "a garbage truck",
               ["rubbish truck", "trash truck", "garbage", "rubbish truck"],
               hint: "The flies are the buzzing kind."),
        riddle("What can you hold in your right hand but never in your left?",
               "your left hand", ["left hand", "left elbow", "elbow"],
               hint: "It's attached to you."),
        riddle("What starts with T, ends with T, and has T in it?", "a teapot",
               ["tea pot"],
               hint: "You make a hot drink with it."),
        riddle("What is always in front of you but can't be seen?", "the future",
               hint: "It hasn't happened yet."),
        riddle("What flies without wings?", "time",
               hint: "It flies when you're having fun."),
        riddle("If you drop me I'll crack, but smile at me and I'll smile back. What am I?",
               "a mirror",
               hint: "You look into it every morning."),
        riddle("What has a thumb and four fingers but isn't alive?", "a glove", ["mitten"],
               hint: "You wear it when it's cold."),
        riddle("Where does Friday come before Thursday?", "the dictionary", ["dictionary"],
               hint: "Think alphabetical order."),
        riddle("What has thirteen hearts but no other body parts?", "a deck of cards",
               ["cards", "deck", "playing cards"],
               hint: "You play games with it."),
        riddle("What can't talk, but will answer when you speak to it?", "an echo",
               hint: "Shout into a canyon and you'll hear it."),
        riddle("The more you take, the more you leave behind. What are they?", "footsteps",
               ["steps", "footprints", "foot prints"],
               hint: "You make them when you walk."),
        riddle("What kind of tree can you carry in your hand?", "a palm", ["palm tree"],
               hint: "It's also part of your hand."),
        riddle("What goes up and down the stairs without moving?", "a carpet", ["rug", "railing", "banister"],
               hint: "It covers the steps."),
        riddle("What word is spelled wrong in every dictionary?", "wrong",
               hint: "Listen to the question very carefully."),
        riddle("Which is heavier: a kilo of feathers or a kilo of bricks?", "neither",
               ["same", "equal", "both", "they weigh the same"],
               hint: "A kilo is a kilo."),
        riddle("What has cities but no houses, forests but no trees, and water but no fish?",
               "a map", ["atlas"],
               hint: "You'd use it to plan a road trip."),
        riddle("What has bark but no bite?", "a tree",
               hint: "It grows leaves."),
        riddle("What do you call a sleeping dinosaur?", "a dino-snore", ["dino snore", "dinosnore", "snore"],
               hint: "Think about the noise it makes at night."),
        riddle("What kind of bow can never be tied?", "a rainbow",
               hint: "You see it after the rain."),
        riddle("What is so fragile that saying its name breaks it?", "silence",
               hint: "Shhh."),
        riddle("What has one head, one foot and four legs?", "a bed",
               hint: "You sleep in it."),
        riddle("What can you serve but never eat?", "a tennis ball", ["ball", "volleyball"],
               hint: "Think sports."),
        riddle("What is easy to get into but hard to get out of?", "trouble",
               hint: "Kids in the back seat are experts at it."),
        riddle("What kind of band never plays any music?", "a rubber band",
               ["elastic band", "rubber"],
               hint: "It's stretchy."),
        riddle("What has lots of eyes but can't see?", "a potato",
               hint: "You can make fries out of it."),
        riddle("What is orange and sounds like a parrot?", "a carrot",
               hint: "Bunnies love it."),
        riddle("What two things can you never eat for breakfast?", "lunch and dinner",
               ["lunch", "dinner"],
               hint: "Think about meals."),
        riddle("What has branches but no fruit, no trunk and no leaves?", "a bank",
               hint: "It's where money lives."),
        riddle("What goes up when the rain comes down?", "an umbrella",
               hint: "It keeps you dry."),
        riddle("Why are fish so smart?", "because they live in schools", ["school", "schools"],
               hint: "Where do kids go to learn?"),
        riddle("What tastes better than it smells?", "your tongue", ["tongue"],
               hint: "It's in your mouth."),
        riddle("What runs all the way around a house but never moves?", "a fence", ["wall"],
               hint: "It keeps the dog in the yard."),
        riddle("What gets sharper the more you use it?", "your brain", ["brain", "mind"],
               hint: "It's working hard right now."),
        riddle("What is black when you buy it, red when you use it, and gray when you throw it away?",
               "charcoal", ["coal"],
               hint: "It's used for barbecues."),
        riddle("What has a ring but no finger?", "a telephone", ["phone", "bell", "doorbell"],
               hint: "Ring ring!"),
        riddle("What has a bottom at the top?", "your legs", ["leg"],
               hint: "You walk on them."),
        riddle("Forward I'm heavy, but backward I'm not. What am I?", "a ton",
               hint: "Spell it backwards."),
        riddle("What kind of cup can't hold water?", "a cupcake", ["cup cake"],
               hint: "It has frosting on top."),
        riddle("What has to be answered but never asks a question?", "a doorbell",
               ["phone", "telephone", "door"],
               hint: "Ding dong!"),
        riddle("What do you call a dog that does magic tricks?", "a labracadabrador",
               ["labrador", "labracadabra"],
               hint: "A dog breed plus a magic word."),
        riddle("What has a spine but no bones?", "a book",
               hint: "It sits on a shelf."),
        riddle("What travels faster: heat or cold?", "heat",
               ["hot"],
               hint: "You can catch one of them.",
               fact: "Because you can catch a cold!"),
    ]

    // MARK: Quiz (fun facts)

    static let quiz: [TravelItem] = [
        quiz("What's the only mammal that can really fly?", "a bat", ["bats"],
             hint: "It sleeps upside down.",
             fact: "About one in every five kinds of mammal is a bat!"),
        quiz("How many hearts does an octopus have?", "three", ["3"],
             hint: "More than two, fewer than four.",
             fact: "And its blood is blue!"),
        quiz("What's the biggest planet in our solar system?", "Jupiter",
             hint: "It has a giant red spot.",
             fact: "More than a thousand Earths could fit inside it."),
        quiz("What color is a polar bear's skin?", "black",
             hint: "It's not white!",
             fact: "Their fur is actually see-through. It just looks white."),
        quiz("How many legs does an insect have?", "six", ["6"],
             hint: "Fewer than a spider.",
             fact: "Spiders have eight, so a spider is not an insect at all."),
        quiz("What's the hottest planet in our solar system?", "Venus",
             hint: "It's not the closest one to the Sun.",
             fact: "Its thick clouds trap the heat, so it's even hotter than Mercury."),
        quiz("What sweet, sticky food do bees make?", "honey",
             hint: "Winnie the Pooh loves it.",
             fact: "Honey never goes bad. People have found honey in ancient Egyptian tombs that was still good."),
        quiz("What's the biggest animal that has ever lived?", "the blue whale", ["whale"],
             hint: "It lives in the ocean.",
             fact: "Its heart is about the size of a small car."),
        quiz("How many sides does a hexagon have?", "six", ["6"],
             hint: "Think of a honeycomb.",
             fact: "Bees build hexagons because it's the strongest shape for the least wax."),
        quiz("What's the closest star to Earth?", "the Sun",
             hint: "You see it every day.",
             fact: "Its light takes about eight minutes to reach us."),
        quiz("Which country is home to kangaroos?", "Australia",
             hint: "It's a country and a continent.",
             fact: "There are more kangaroos in Australia than people."),
        quiz("What do caterpillars turn into?", "a butterfly", ["butterflies", "moth"],
             hint: "They have beautiful wings."),
        quiz("Which planet is famous for its rings?", "Saturn",
             hint: "It's the sixth planet from the Sun.",
             fact: "Saturn is so light that it would float in a giant bathtub."),
        quiz("What's the tallest animal in the world?", "the giraffe",
             hint: "Very long neck.",
             fact: "A giraffe's tongue is about half a meter long, and it's dark blue."),
        quiz("How many days are in a leap year?", "366",
             ["three hundred sixty six", "three hundred and sixty six", "three sixty six"],
             hint: "One more than usual."),
        quiz("What's the largest ocean on Earth?", "the Pacific", ["pacific ocean"],
             hint: "It's between Asia and America.",
             fact: "It's bigger than all the land on Earth put together."),
        quiz("What's the fastest land animal?", "the cheetah",
             hint: "A big spotted cat.",
             fact: "It can go from zero to a hundred kilometers an hour in about three seconds."),
        quiz("About how many bones are in an adult human body?", "206",
             ["two hundred six", "two hundred and six", "two oh six"],
             hint: "Just over two hundred.",
             fact: "Babies are born with around three hundred. Some join together as they grow."),
        quiz("What's the biggest continent?", "Asia",
             hint: "India and China are on it."),
        quiz("What's the name of our galaxy?", "the Milky Way", ["milky way"],
             hint: "It sounds like a chocolate bar."),
        quiz("What gas do we need to breathe in to stay alive?", "oxygen",
             hint: "Its symbol is the letter O.",
             fact: "Most of the oxygen we breathe comes from tiny plants in the ocean."),
        quiz("What's the smallest planet in our solar system?", "Mercury",
             hint: "It's the closest one to the Sun.",
             fact: "A year on Mercury is only 88 days long."),
        quiz("How many colors are in a rainbow?", "seven", ["7"],
             hint: "Red, orange, yellow... keep counting."),
        quiz("Which African animal has black and white stripes?", "the zebra",
             hint: "It looks like a stripy horse.",
             fact: "No two zebras have the same stripes, just like fingerprints."),
        quiz("What's a baby kangaroo called?", "a joey",
             hint: "It's also a boy's name."),
        quiz("What's the hardest natural material on Earth?", "diamond",
             hint: "It sparkles on rings."),
        quiz("What's the longest river in the world?", "the Nile", ["amazon"],
             hint: "It flows through Egypt.",
             fact: "Some scientists say the Amazon is longer. They're still arguing about it!"),
        quiz("What do you call an animal that only eats plants?", "a herbivore",
             ["herbivores", "vegetarian"],
             hint: "Cows and rabbits are one."),
        quiz("What's the capital city of Japan?", "Tokyo",
             hint: "It hosted the Olympics in 2021."),
        quiz("What's the biggest land animal alive today?", "the elephant",
             ["african elephant"],
             hint: "It has a trunk.",
             fact: "Elephants can recognize themselves in a mirror."),
        quiz("At what temperature in Celsius does water boil?", "100 degrees",
             ["100", "hundred", "one hundred"],
             hint: "A nice round number."),
        quiz("What's the biggest country in the world?", "Russia",
             hint: "It's so wide it has eleven time zones."),
        quiz("What color do you get when you mix blue and yellow?", "green",
             hint: "The color of grass."),
        quiz("What force keeps our feet on the ground?", "gravity",
             hint: "An apple supposedly fell on Isaac Newton's head."),
        quiz("How many players does a cricket team have on the field?", "eleven", ["11"],
             hint: "Same as a football team."),
        quiz("What do you call a group of crows?", "a murder",
             hint: "It sounds spooky.",
             fact: "Crows can remember human faces, and they hold grudges!"),
        quiz("Which planet spins on its side?", "Uranus",
             hint: "It's the seventh planet from the Sun."),
        quiz("Which fruit wears its seeds on the outside?", "a strawberry",
             ["strawberries"],
             hint: "It's small and red.",
             fact: "An average strawberry has about two hundred seeds."),
        quiz("What's a baby goat called?", "a kid", ["kids"],
             hint: "It's the same word grown-ups use for children."),
        quiz("What's a baby cow called?", "a calf",
             hint: "It rhymes with half."),
        quiz("Which sport is played at Wimbledon?", "tennis",
             hint: "Rackets and a fuzzy yellow ball."),
        quiz("Which furry mammal lays eggs and has a duck's bill?", "the platypus",
             hint: "It lives in Australia."),
        quiz("What do pandas mostly eat?", "bamboo",
             hint: "Tall and green.",
             fact: "Pandas spend about twelve hours a day eating."),
        quiz("What's the coldest continent?", "Antarctica",
             hint: "Penguins live there."),
        quiz("Who painted the Mona Lisa?", "Leonardo da Vinci",
             ["da vinci", "davinci", "leonardo"],
             hint: "He was also a famous inventor."),
        quiz("What's the largest organ of the human body?", "the skin",
             hint: "It covers all of you.",
             fact: "You shed thousands of skin cells every single minute."),
        quiz("In which country is the Taj Mahal?", "India",
             hint: "It's in the city of Agra."),
        quiz("What's the name of Harry Potter's owl?", "Hedwig",
             hint: "She's snowy white."),
        quiz("Raisins are dried versions of which fruit?", "grapes", ["grape"],
             hint: "They grow in bunches."),
        quiz("Which lizard is famous for changing color?", "the chameleon",
             hint: "Its eyes can look in two directions at once."),
        quiz("What language do most people speak in Brazil?", "Portuguese",
             hint: "It's not Spanish!"),
        quiz("What's the slowest mammal on Earth?", "the sloth",
             hint: "It hangs in trees all day.",
             fact: "Sloths climb down from their tree about once a week, just to poop!"),
        quiz("Which country did pizza come from?", "Italy",
             hint: "Think of Rome."),
        quiz("What's the name of the frozen water floating in the sea?", "an iceberg",
             ["ice berg", "icebergs"],
             hint: "One sank the Titanic.",
             fact: "About ninety percent of an iceberg is hidden under the water."),
        quiz("How many minutes are in two hours?", "120",
             ["one hundred twenty", "one hundred and twenty", "a hundred and twenty"],
             hint: "Sixty plus sixty."),
        quiz("Which animal is known as the ship of the desert?", "the camel",
             hint: "It has a hump or two.",
             fact: "Camel humps store fat, not water."),
        quiz("What's the name of the force that makes a compass point north?",
             "magnetism", ["magnet", "magnetic field", "magnets"],
             hint: "Fridge ___."),
        quiz("What is a baby frog called?", "a tadpole", ["polliwog"],
             hint: "It swims and has a tail."),
        quiz("Which planet is called the Red Planet?", "Mars",
             hint: "Rovers are exploring it right now.",
             fact: "It's red because its dust is full of rust."),
        quiz("How many continents are there?", "seven", ["7"],
             hint: "Same as the days of the week."),
        quiz("Which bird can't fly but is an amazing swimmer?", "the penguin",
             hint: "It wears a tuxedo."),
        quiz("What do you call a scientist who studies dinosaurs?", "a paleontologist",
             ["palaeontologist", "paleontologists"],
             hint: "It starts with P and it's a long word."),
    ]
}
