"""Static content pools for the party and mid-group games.

Kept in one module so prompts can be extended without touching engine logic.
Indian and Western content sit side by side deliberately -- the catalog is meant
to work for a mixed living room.
"""

# ---- Bluff It: an obscure fact with a blank the players fill with fakes -----
BLUFF_FACTS = [
    ("The world's largest ____ weighs over 900 kilograms.", "pumpkin"),
    ("In Japan it is traditional to eat ____ on Christmas Day.", "fried chicken"),
    ("The national animal of Scotland is the ____.", "unicorn"),
    ("A group of flamingos is called a ____.", "flamboyance"),
    ("The first item ever sold on eBay was a broken ____.", "laser pointer"),
    ("Cows have best friends and get stressed when ____.", "separated"),
    ("The inventor of the Pringles can is buried in ____.", "a Pringles can"),
    ("Bananas are berries, but ____ are not.", "strawberries"),
    ("The shortest war in history lasted ____ minutes.", "38"),
    ("Octopuses have ____ hearts.", "three"),
    ("In India, the world's largest ____ is held every 12 years.", "gathering"),
    ("The Eiffel Tower can be ____ centimetres taller in summer.", "15"),
    ("A shrimp's heart is located in its ____.", "head"),
    ("The dot over a lowercase i is called a ____.", "tittle"),
    ("Wombat droppings are shaped like ____.", "cubes"),
]

# ---- Herd: answer the way you think the crowd will ---------------------------
HERD_PROMPTS = [
    "Name a breakfast food.",
    "Name a colour.",
    "Name something you find in a kitchen.",
    "Name a Bollywood actor.",
    "Name a cricket shot.",
    "Name a wild animal.",
    "Name something you take on holiday.",
    "Name an Indian street food.",
    "Name a superhero.",
    "Name something that is cold.",
    "Name a school subject.",
    "Name a fruit that is not an apple.",
    "Name a mode of transport.",
    "Name something in your pocket right now.",
    "Name a festival.",
]

# ---- Emoji Movie: secret title, describe it in emoji -------------------------
EMOJI_TITLES = [
    "Titanic", "The Lion King", "Jurassic Park", "Finding Nemo", "Frozen",
    "Sholay", "Dangal", "3 Idiots", "Lagaan", "Bahubali",
    "Harry Potter", "The Matrix", "Toy Story", "Spider-Man", "Up",
    "Jaws", "Home Alone", "Inception", "Zootopia", "Cars",
    "Ra.One", "Krrish", "PK", "Queen", "Gully Boy",
]

# ---- Name Place Animal Thing ------------------------------------------------
NPAT_LETTERS = "ABCDGHJKLMNPRSTV"     # letters with enough easy answers
NPAT_FIELDS = ["name", "place", "animal", "thing"]

# ---- Antakshari: song-chain letters -----------------------------------------
ANTAKSHARI_LETTERS = "ABCDGHJKLMNPRSTVY"

# ---- Odd One Out: shared location, one player is the spy --------------------
SPY_LOCATIONS = [
    "Railway station", "Wedding hall", "Cricket stadium", "Hospital",
    "Space station", "Beach resort", "Movie theatre", "School classroom",
    "Airplane", "Submarine", "Bank vault", "Tea plantation",
    "Night market", "Ski lodge", "Art museum", "Police station",
    "Pirate ship", "Casino floor", "Zoo", "Temple",
]

# ---- Cipher Grid: the shared 5x5 word board ---------------------------------
CIPHER_WORDS = [
    "TIGER", "MANGO", "ROCKET", "TEMPLE", "RIVER", "CROWN", "DRAGON", "MONSOON",
    "SPICE", "MARBLE", "COMPASS", "LANTERN", "THUNDER", "PEACOCK", "SILK",
    "HARBOUR", "CANNON", "ORBIT", "JUNGLE", "MIRROR", "PALACE", "FALCON",
    "EMBER", "GLACIER", "BAZAAR", "COMET", "SADDLE", "VIOLIN", "ANCHOR",
    "PYRAMID", "WHISTLE", "BAMBOO", "COBRA", "SUNSET", "IVORY", "NEEDLE",
    "GARLAND", "CANYON", "TURBAN", "LOTUS", "SABRE", "MARKET", "PARROT",
    "FOSSIL", "KETTLE", "MEADOW", "SHADOW", "TRIDENT", "WALNUT", "ZEPHYR",
]

# ---- Wavelength: the two ends of the dial ------------------------------------
WAVELENGTH_SPECTRA = [
    ("Cold", "Hot"), ("Cheap", "Expensive"), ("Underrated", "Overrated"),
    ("Boring", "Exciting"), ("Round", "Pointy"), ("Useless", "Essential"),
    ("Quiet", "Loud"), ("Casual", "Formal"), ("Scary", "Comforting"),
    ("Old-fashioned", "Modern"), ("Sour", "Sweet"), ("Weak", "Powerful"),
    ("Fictional", "Real"), ("Simple", "Complicated"), ("Rude", "Polite"),
]

# ---- Sealed Auction: lots to bid on -----------------------------------------
AUCTION_LOTS = [
    ("A private island", 10), ("The last slice of pizza", 2),
    ("A time machine", 10), ("A lifetime of free chai", 6),
    ("Your neighbour's Wi-Fi password", 3), ("A talking parrot", 4),
    ("Front-row World Cup final tickets", 8), ("A haunted mansion", 5),
    ("An unlimited flight pass", 9), ("A vintage Ambassador car", 6),
    ("A star named after you", 4), ("A robot that does your chores", 8),
]

# ---- KBC Hot Seat: ladder quiz ----------------------------------------------
KBC_QUESTIONS = [
    ("Which planet is known as the Red Planet?",
     ["Mars", "Venus", "Jupiter", "Mercury"], 0),
    ("Who wrote the Indian national anthem?",
     ["Rabindranath Tagore", "Bankim Chandra", "Sarojini Naidu", "Premchand"], 0),
    ("What is the capital of Australia?",
     ["Canberra", "Sydney", "Melbourne", "Perth"], 0),
    ("How many players are on a cricket team?",
     ["11", "10", "12", "9"], 0),
    ("Which gas do plants absorb?",
     ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"], 0),
    ("The Taj Mahal is in which city?",
     ["Agra", "Delhi", "Jaipur", "Lucknow"], 0),
    ("What is the largest ocean?",
     ["Pacific", "Atlantic", "Indian", "Arctic"], 0),
    ("Who painted the Mona Lisa?",
     ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"], 0),
    ("Which is the longest river in India?",
     ["Ganga", "Yamuna", "Godavari", "Narmada"], 0),
    ("How many continents are there?",
     ["7", "5", "6", "8"], 0),
    ("What is the chemical symbol for gold?",
     ["Au", "Ag", "Gd", "Go"], 0),
    ("Which country hosted the 2016 Olympics?",
     ["Brazil", "China", "Russia", "Japan"], 0),
    ("How many zeros are in one crore?",
     ["6", "7", "8", "5"], 1),
    ("Which vitamin is also called ascorbic acid?",
     ["A", "B12", "C", "D"], 2),
    ("The pink ball is used in which format of cricket?",
     ["T20", "ODI", "Day-night Test", "The Hundred"], 2),
    ("Which country won the 2023 Cricket World Cup?",
     ["India", "England", "Australia", "New Zealand"], 2),
    ("Who is the author of 'The God of Small Things'?",
     ["Arundhati Roy", "Jhumpa Lahiri", "Salman Rushdie", "Vikram Seth"], 0),
    ("Which gas is used to fill balloons that float?",
     ["Oxygen", "Hydrogen", "Helium", "Nitrogen"], 2),
    ("What is the full form of 'ATM'?",
     ["Automated Teller Machine", "Automatic Transaction Mode", "Any Time Money", "Automated Transfer Mode"], 0),
    ("Who was the first Indian to win an individual Olympic gold medal?",
     ["Abhinav Bindra", "Neeraj Chopra", "P.V. Sindhu", "Milkha Singh"], 0),
    ("The Statue of Unity is in which Indian state?",
     ["Maharashtra", "Gujarat", "Rajasthan", "Madhya Pradesh"], 1),
    ("Which planet rotates on its side?",
     ["Venus", "Uranus", "Neptune", "Mercury"], 1),
    ("Who was the first Indian woman to win an Olympic medal?",
     ["P.T. Usha", "Karnam Malleswari", "Mary Kom", "Saina Nehwal"], 1),
    ("What is the study of coins called?",
     ["Philately", "Numismatics", "Paleontology", "Cartography"], 1),
    ("Which is the largest island in the world?",
     ["Borneo", "Greenland", "Madagascar", "Sumatra"], 1),
    ("The Dronacharya Award is given for excellence in what?",
     ["Sports coaching", "Science", "Literature", "Music"], 0),
    ("Which river is called the 'Sorrow of Bihar'?",
     ["Ganga", "Kosi", "Gandak", "Son"], 1),
    ("Who invented the telephone?",
     ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], 1),
    ("Which is the deepest lake in the world?",
     ["Caspian Sea", "Lake Baikal", "Lake Tanganyika", "Great Slave Lake"], 1),
    ("The slogan 'Jai Jawan Jai Kisan' was given by whom?",
     ["Mahatma Gandhi", "Lal Bahadur Shastri", "Indira Gandhi", "Jawaharlal Nehru"], 1),
    ("Which country is the largest producer of coffee?",
     ["Colombia", "Vietnam", "Brazil", "Ethiopia"], 2),
    ("What is the hardest known mineral?",
     ["Quartz", "Topaz", "Diamond", "Corundum"], 2),
    ("Which festival marks the beginning of the Malayalam new year?",
     ["Onam", "Vishu", "Pongal", "Bihu"], 1),
    ("What is the currency of the United Kingdom?",
     ["Euro", "Dollar", "Pound Sterling", "Franc"], 2),
    ("Which Indian state has the longest coastline?",
     ["Tamil Nadu", "Gujarat", "Maharashtra", "Andhra Pradesh"], 1),
    ("Who, along with Tenzing Norgay, first summited Mount Everest?",
     ["Edmund Hillary", "George Mallory", "Reinhold Messner", "Junko Tabei"], 0),
    ("Which organ in the human body produces insulin?",
     ["Liver", "Pancreas", "Kidney", "Stomach"], 1),
    ("The Golden Temple is located in which city?",
     ["Amritsar", "Ludhiana", "Jalandhar", "Patiala"], 0),
    ("Which is the smallest bone in the human body?",
     ["Stapes", "Phalanx", "Ulna", "Coccyx"], 0),
    ("Who painted 'The Starry Night'?",
     ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dali"], 1),
    ("Which Indian classical dance form comes from Kerala?",
     ["Bharatanatyam", "Kathakali", "Odissi", "Kuchipudi"], 1),
    ("The Quit India movement was launched in which year?",
     ["1920", "1930", "1942", "1947"], 2),
    ("Which metal is used in the filament of a light bulb?",
     ["Copper", "Tungsten", "Aluminium", "Iron"], 1),
    ("Who is known as the 'Missile Man of India'?",
     ["Vikram Sarabhai", "A.P.J. Abdul Kalam", "Homi Bhabha", "C.V. Raman"], 1),
    ("Which is the largest gland in the human body?",
     ["Thyroid", "Liver", "Pancreas", "Pituitary"], 1),
    ("The World Wide Web was invented by whom?",
     ["Bill Gates", "Tim Berners-Lee", "Vint Cerf", "Steve Jobs"], 1),
    ("How many players of a kabaddi team are on the court?",
     ["5", "6", "7", "9"], 2),
    ("Which Indian film was India's first talkie?",
     ["Alam Ara", "Raja Harishchandra", "Shirin Farhad", "Laila Majnu"], 0),
    ("The Nobel Prize is named after which inventor?",
     ["Alfred Nobel", "Marie Curie", "Albert Einstein", "Thomas Edison"], 0),
    ("Which city hosted the 2020 Summer Olympics?",
     ["Paris", "Tokyo", "Rio de Janeiro", "Los Angeles"], 1),
    ("What is the national sport of China?",
     ["Table tennis", "Badminton", "Basketball", "Football"], 0),
    ("Which desert is the largest hot desert in the world?",
     ["Gobi", "Sahara", "Kalahari", "Thar"], 1),
    ("Who was the first Indian to win a Nobel Prize?",
     ["C.V. Raman", "Rabindranath Tagore", "Mother Teresa", "Amartya Sen"], 1),
    ("Which is the largest freshwater lake in the world by surface area?",
     ["Caspian Sea", "Lake Superior", "Lake Victoria", "Lake Baikal"], 1),
    ("The Chipko Movement was started to protect what?",
     ["Rivers", "Forests", "Wildlife", "Mountains"], 1),
    ("Which Indian state is known as the 'Land of Five Rivers'?",
     ["Uttar Pradesh", "Punjab", "Haryana", "Rajasthan"], 1),
    ("Who discovered penicillin?",
     ["Louis Pasteur", "Alexander Fleming", "Robert Koch", "Joseph Lister"], 1),
    ("Which is the fastest bird in the world?",
     ["Golden eagle", "Peregrine falcon", "Albatross", "Swift"], 1),
    ("The Red Fort was built by which Mughal emperor?",
     ["Babur", "Akbar", "Shah Jahan", "Humayun"], 2),
    ("Which country is the origin of the Olympic Games?",
     ["Italy", "Greece", "France", "Egypt"], 1),
    ("What does 'IPL' stand for?",
     ["Indian Premier League", "International Premier League", "India Pro League", "Indian Pro League"], 0),
    ("Which Indian state celebrates the Hornbill Festival?",
     ["Assam", "Nagaland", "Manipur", "Meghalaya"], 1),
    ("Who was the first woman Prime Minister of India?",
     ["Sonia Gandhi", "Indira Gandhi", "Pratibha Patil", "Sarojini Naidu"], 1),
    ("Which is the longest bone in the human body?",
     ["Humerus", "Femur", "Tibia", "Fibula"], 1),
    ("The Eiffel Tower was built for which event?",
     ["1889 World's Fair", "French Revolution centenary", "1900 Olympics", "Napoleon's coronation"], 0),
    ("Which Indian cricketer has scored the most ODI centuries?",
     ["Sachin Tendulkar", "Virat Kohli", "Rohit Sharma", "Rahul Dravid"], 1),
    ("What is the chemical formula of common salt?",
     ["NaCl", "KCl", "CaCO3", "NaOH"], 0),
    ("Which country is known as the 'Land of the Midnight Sun'?",
     ["Norway", "Sweden", "Finland", "Iceland"], 0),
    ("Who wrote 'Wings of Fire'?",
     ["A.P.J. Abdul Kalam", "Jawaharlal Nehru", "M.K. Gandhi", "S. Radhakrishnan"], 0),
    ("Which is the largest cricket stadium in India by capacity?",
     ["Eden Gardens", "Narendra Modi Stadium", "Wankhede", "M. Chinnaswamy"], 1),
    ("The Great Barrier Reef is in which ocean?",
     ["Atlantic", "Pacific", "Indian", "Arctic"], 1),
    ("Which Indian mathematician is credited with formalizing the concept of zero?",
     ["Aryabhata", "Brahmagupta", "Bhaskara", "Ramanujan"], 1),
    ("How many spokes are in the Ashoka Chakra?",
     ["12", "16", "20", "24"], 3),
    ("Which city is the headquarters of the United Nations?",
     ["Geneva", "New York", "Paris", "Vienna"], 1),
    ("The 'Mona Lisa' is displayed in which museum?",
     ["British Museum", "Louvre", "Prado", "Uffizi"], 1),
    ("Which Indian state is the largest producer of tea?",
     ["Kerala", "Assam", "West Bengal", "Tamil Nadu"], 1),
    ("Who was the first Indian woman to win the Miss Universe title?",
     ["Aishwarya Rai", "Sushmita Sen", "Lara Dutta", "Priyanka Chopra"], 1),
    ("Which planet has a day longer than its year?",
     ["Mercury", "Venus", "Mars", "Jupiter"], 1),
    ("The Suez Canal connects which two seas?",
     ["Red Sea and Mediterranean Sea", "Arabian Sea and Red Sea", "Black Sea and Mediterranean Sea", "Caspian Sea and Black Sea"], 0),
    ("Which Indian festival is known as the 'Festival of Colors'?",
     ["Diwali", "Holi", "Navratri", "Pongal"], 1),
    ("Who is the author of 'Harry Potter'?",
     ["J.K. Rowling", "Roald Dahl", "J.R.R. Tolkien", "C.S. Lewis"], 0),
    ("The Taj Mahal is made primarily of which stone?",
     ["Red sandstone", "White marble", "Granite", "Limestone"], 1),
    ("Which country invented paper currency?",
     ["Egypt", "China", "Greece", "Rome"], 1),
    ("Who was the first Indian to travel to space?",
     ["Kalpana Chawla", "Rakesh Sharma", "Sunita Williams", "Ravish Malhotra"], 1),
    ("Which is the national aquatic animal of India?",
     ["Ganges river dolphin", "Blue whale", "Olive ridley turtle", "Dugong"], 0),
    ("Which Indian state has the famous 'Valley of Flowers'?",
     ["Himachal Pradesh", "Uttarakhand", "Sikkim", "Jammu and Kashmir"], 1),
    ("Who composed the Indian national song 'Vande Mataram'?",
     ["Rabindranath Tagore", "Bankim Chandra Chatterjee", "Sarojini Naidu", "Subhas Chandra Bose"], 1),
    ("Which is the smallest state of India by area?",
     ["Goa", "Sikkim", "Tripura", "Manipur"], 0),
    ("The classic Olympic motto is what?",
     ["Faster, Higher, Stronger", "Victory or Death", "Play Fair", "One World One Dream"], 0),
    ("Which Indian city is famous for the Charminar?",
     ["Delhi", "Hyderabad", "Lucknow", "Bhopal"], 1),
    ("Who was the first Governor-General of independent India?",
     ["Lord Mountbatten", "C. Rajagopalachari", "Jawaharlal Nehru", "Sardar Patel"], 1),
    ("Which is the largest delta in the world?",
     ["Nile Delta", "Ganges-Brahmaputra Delta", "Mekong Delta", "Amazon Delta"], 1),
    ("The Panchatantra was written in which language?",
     ["Hindi", "Sanskrit", "Pali", "Prakrit"], 1),
    ("Which Indian state is called the 'Spice Garden of India'?",
     ["Kerala", "Karnataka", "Tamil Nadu", "Assam"], 0),
    ("Who was the founder of the Maurya Empire?",
     ["Ashoka", "Chandragupta Maurya", "Bindusara", "Chanakya"], 1),
    ("Which is the highest civilian award in India?",
     ["Padma Vibhushan", "Bharat Ratna", "Padma Bhushan", "Ashoka Chakra"], 1),
    ("The Gateway of India was built to commemorate whose visit?",
     ["Queen Victoria", "King George V", "Lord Curzon", "Winston Churchill"], 1),
    ("Which planet is called the 'Morning Star'?",
     ["Mercury", "Venus", "Mars", "Jupiter"], 1),
    ("Who was the first Indian woman IPS officer?",
     ["Kiran Bedi", "Anna Rajam Malhotra", "Kanchan Chaudhary", "Sanjukta Parashar"], 0),
    ("Which Indian state has separate summer and winter capitals?",
     ["Himachal Pradesh", "Jammu and Kashmir", "Uttarakhand", "Maharashtra"], 1),
    ("The Dandi March is also known as what?",
     ["Salt Satyagraha", "Non-Cooperation Movement", "Civil Disobedience", "Quit India"], 0),
    ("Which is the longest railway platform in India?",
     ["Gorakhpur", "Kharagpur", "Kollam", "Bilaspur"], 0),
    ("Who wrote the 'Arthashastra'?",
     ["Chanakya", "Kalidasa", "Panini", "Patanjali"], 0),
    ("Which Indian river is called the 'Dakshin Ganga'?",
     ["Krishna", "Godavari", "Kaveri", "Narmada"], 1),
    ("The Kumbh Mela is held every how many years at one site?",
     ["3", "6", "12", "4"], 2),
    ("Which is the largest living bird?",
     ["Emu", "Ostrich", "Albatross", "Condor"], 1),
    ("Who was the first Indian to win an Oscar?",
     ["Satyajit Ray", "Bhanu Athaiya", "A.R. Rahman", "Resul Pookutty"], 1),
    ("Which country is the largest producer of tea in the world?",
     ["India", "China", "Sri Lanka", "Kenya"], 1),
    ("The National Anthem of India was first sung in which year?",
     ["1911", "1947", "1950", "1905"], 0),
    ("Which Indian state is famous for the Sun Temple at Konark?",
     ["West Bengal", "Odisha", "Bihar", "Jharkhand"], 1),
    ("Who was the first Indian woman to climb Mount Everest?",
     ["Santosh Yadav", "Bachendri Pal", "Premlata Agarwal", "Arunima Sinha"], 1),
    ("Which is the oldest mountain range in India?",
     ["Himalayas", "Aravalli", "Western Ghats", "Vindhya"], 1),
    ("The Jallianwala Bagh massacre happened in which city?",
     ["Lahore", "Amritsar", "Delhi", "Lucknow"], 1),
    ("Which Indian city is known as the 'City of Joy'?",
     ["Mumbai", "Kolkata", "Chennai", "Delhi"], 1),
    ("Who was the founder of the Mughal Empire in India?",
     ["Akbar", "Babur", "Humayun", "Sher Shah"], 1),
    ("Which is the largest desert in India?",
     ["Thar", "Rann of Kutch", "Ladakh", "Spiti"], 0),
]

KBC_LADDER = [1000, 2000, 5000, 10000, 20000, 40000, 80000,
              160000, 320000, 640000, 1250000, 2500000]

# ---- Bollywood Charades ------------------------------------------------------
CHARADES_TITLES = [
    "Sholay", "Dilwale Dulhania Le Jayenge", "3 Idiots", "Lagaan", "Dangal",
    "Bahubali", "Andaz Apna Apna", "Munna Bhai MBBS", "Zindagi Na Milegi Dobara",
    "Queen", "Gully Boy", "Chak De India", "Swades", "Rang De Basanti",
    "Kabhi Khushi Kabhie Gham", "Om Shanti Om", "Golmaal", "Hera Pheri",
    "Taare Zameen Par", "Barfi",
]

# ---- Atlas: place-name chain seeds ------------------------------------------
ATLAS_SEEDS = ["India", "Nepal", "Kolkata", "Madrid", "Norway", "Cairo"]

# A generous but finite validation set. Solo Atlas checks against this; in a
# multiplayer game the room adjudicates, which is how it is played anyway.
ATLAS_PLACES = {
    "india", "indonesia", "iran", "iraq", "ireland", "israel", "italy",
    "japan", "jordan", "jamaica", "kenya", "kuwait", "korea", "kolkata",
    "nepal", "norway", "nigeria", "netherlands", "new zealand", "nagpur",
    "australia", "austria", "argentina", "algeria", "afghanistan", "agra",
    "spain", "sweden", "switzerland", "singapore", "sudan", "surat", "sydney",
    "delhi", "denmark", "dubai", "dhaka", "darjeeling",
    "france", "finland", "fiji", "frankfurt",
    "egypt", "ecuador", "england", "ethiopia",
    "germany", "greece", "ghana", "goa", "guwahati",
    "hungary", "hyderabad", "haryana", "havana",
    "mexico", "morocco", "malaysia", "mumbai", "madrid", "manila", "moscow",
    "canada", "china", "chile", "colombia", "chennai", "cairo", "cuba",
    "brazil", "belgium", "bhutan", "bangladesh", "bangalore", "berlin",
    "portugal", "poland", "peru", "pakistan", "paris", "pune", "prague",
    "turkey", "thailand", "tanzania", "tokyo", "toronto", "tunisia",
    "russia", "romania", "rwanda", "rome", "riyadh", "raipur",
    "ukraine", "uganda", "uruguay", "uzbekistan",
    "vietnam", "venezuela", "vienna", "vadodara",
    "yemen", "york", "yokohama",
    "zambia", "zimbabwe", "zurich",
    "oman", "oslo", "ottawa", "osaka",
    "lebanon", "libya", "laos", "london", "lucknow", "lisbon",
}

# ---- Most Likely To: secret-ballot party voting -----------------------------
MOST_LIKELY_PROMPTS = [
    "Most likely to fall asleep during a family movie night.",
    "Most likely to take charge of the music at a party.",
    "Most likely to be late to a wedding.",
    "Most likely to eat the most at a buffet.",
    "Most likely to win an argument with mom.",
    "Most likely to forget where they parked the car.",
    "Most likely to take a hundred photos and post none.",
    "Most likely to start dancing first at a sangeet.",
    "Most likely to know all the cricket scores by heart.",
    "Most likely to order extra dessert.",
    "Most likely to lose their phone inside their own house.",
    "Most likely to give the best wedding speech.",
    "Most likely to call the family group chat instead of texting.",
    "Most likely to finish everyone else's leftovers.",
    "Most likely to plan the next family trip.",
    "Most likely to binge a whole series in one night.",
    "Most likely to be the peacemaker in a family debate.",
    "Most likely to bring the best homemade dish to a potluck.",
    "Most likely to get lost but refuse to ask for directions.",
    "Most likely to remember everyone's birthday.",
    "Most likely to fall for a WhatsApp forward.",
    "Most likely to be the first one ready for an outing.",
    "Most likely to steal the blanket at night.",
    "Most likely to host the next Diwali party.",
    "Most likely to sing in the car like nobody is listening.",
]


# ---------------------------------------------------------------------------
# Extra content so a full game night doesn't recycle the same prompts.
# Appended (de-duplicated) rather than interleaved so the lists above stay
# easy to review on their own.
# ---------------------------------------------------------------------------

def _extend(target, extra):
    seen = {item if isinstance(item, str) else item[0] for item in target}
    for item in extra:
        key = item if isinstance(item, str) else item[0]
        if key not in seen:
            target.append(item)
            seen.add(key)


_extend(BLUFF_FACTS, [
    ("A group of crows is called a ____.", "murder"),
    ("A group of owls is called a ____.", "parliament"),
    ("The ____ is the only mammal capable of true flight.", "bat"),
    ("An octopus has ____ hearts.", "three"),
    ("A baby kangaroo is called a ____.", "joey"),
    ("Botanically, bananas are classified as ____.", "berries"),
    ("The dot over a lowercase i is called a ____.", "tittle"),
    ("India's national aquatic animal is the Ganges river ____.", "dolphin"),
    ("India's first talkie film, released in 1931, was called ____.", "Alam Ara"),
    ("Wombat droppings are shaped like ____.", "cubes"),
])

_extend(CHARADES_TITLES, [
    "RRR", "Pushpa", "Magadheera", "Eega", "Arjun Reddy", "Pokiri", "Athadu",
    "Ala Vaikunthapurramuloo", "Rangasthalam", "Jersey", "Mahanati",
    "Bommarillu", "Happy Days", "Kalki 2898 AD", "Devdas", "Jab We Met",
    "Taare Zameen Par", "PK", "Bajrangi Bhaijaan", "Kal Ho Naa Ho",
    "Kuch Kuch Hota Hai", "Dhoom", "Krrish", "Jawan", "Pathaan", "Stree",
    "Andhadhun", "Drishyam", "Bhool Bhulaiyaa", "Welcome", "Don",
])

_extend(EMOJI_TITLES, [
    "Avatar", "Star Wars", "The Avengers", "Shrek", "Kung Fu Panda",
    "RRR", "Pushpa", "Eega", "Jab We Met", "Taare Zameen Par", "Ghostbusters",
    "Batman", "Pirates of the Caribbean", "Ice Age", "Minions",
])

_extend(HERD_PROMPTS, [
    "Name a festival.", "Name a cricketer.", "Name a fruit.", "Name an Indian sweet.",
    "Name a Telugu film star.", "Name a city in India.", "Name a vegetable.",
    "Name a pet animal.", "Name something you pack for a trip.", "Name a famous singer.",
    "Name a superhero.", "Name a chutney.", "Name a tea-time snack.", "Name a car brand.",
    "Name a wedding ritual.", "Name a social media app.", "Name something yellow.",
    "Name a dance form.", "Name a street food.", "Name a board game.",
])

_extend(MOST_LIKELY_PROMPTS, [
    "Most likely to forward a fake news message on WhatsApp.",
    "Most likely to cry during a movie.",
    "Most likely to start dancing first at a wedding.",
    "Most likely to forget a friend's birthday.",
    "Most likely to bargain hard with a shopkeeper.",
    "Most likely to become famous.",
    "Most likely to get lost even with Google Maps.",
    "Most likely to order dessert first.",
    "Most likely to reply to messages after three days.",
    "Most likely to survive a zombie apocalypse.",
    "Most likely to sing loudly in the shower.",
    "Most likely to have 100 browser tabs open.",
    "Most likely to plan the next family trip.",
    "Most likely to fall for an online sale.",
    "Most likely to bring home food from a party.",
    "Most likely to win a dance-off.",
    "Most likely to binge a whole series in one night.",
    "Most likely to argue about cricket.",
    "Most likely to oversleep and miss a flight.",
    "Most likely to adopt five dogs.",
])
