"""Content for "The Host Is Lying".

FACTS are (true statement, false twin, why it is true). The false twin changes
one detail, so the two read alike and only the claim itself separates them.
Every item is family friendly and settled fact.

TELL_* pools are the host's tells: phrases the host adds when it is bluffing
(and, deliberately, sometimes when it is not). They are written to sound like
a real person over-selling a story, never like a robot error message.
"""

FACTS = [
    # --- animals and nature
    ("Octopuses have three hearts.", "Octopuses have five hearts.",
     "Two pump blood to the gills and one pumps it around the body."),
    ("Honey stored in a sealed jar can last practically forever.",
     "Honey stored in a sealed jar spoils after about two years.",
     "Honey is so low in water and so acidic that microbes cannot grow in it."),
    ("Dolphins sleep with one half of their brain awake.",
     "Dolphins never sleep at all.",
     "One half rests at a time so they can still surface to breathe."),
    ("An ostrich's eye is bigger than its brain.",
     "An ostrich's brain is bigger than its eye.",
     "Each eye is about the size of a billiard ball."),
    ("Starfish have no brain.",
     "Starfish have a small brain in the middle of their body.",
     "They get by on a ring of nerves and nerve cells in each arm."),
    ("Koalas have fingerprints that look almost like human ones.",
     "Koalas have no fingerprints at all.",
     "Their prints are so similar that they could confuse a crime scene."),
    ("A group of crows is called a murder.",
     "A group of crows is called a choir.",
     "Murder is the old collective noun for crows."),
    ("Butterflies taste with their feet.",
     "Butterflies taste with their wings.",
     "Sensors on their feet tell them if a leaf is good to eat or lay eggs on."),
    ("Bees tell each other where flowers are by doing a waggle dance.",
     "Bees tell each other where flowers are by humming a code.",
     "The angle and length of the dance show direction and distance."),
    ("Cows have a stomach with four chambers.",
     "Cows have a stomach with two chambers.",
     "The four chambers help them digest tough grass."),
    ("There are no wild penguins at the North Pole.",
     "Penguins and polar bears live side by side at the North Pole.",
     "Penguins live in the Southern Hemisphere; polar bears live in the Arctic."),
    ("Cats have a third eyelid.",
     "Cats have no eyelids.",
     "The third eyelid sweeps across the eye to protect and clean it."),
    ("The blue whale is the largest animal known ever to have lived.",
     "The largest animal known ever to have lived was a dinosaur.",
     "Blue whales are bigger than even the biggest dinosaurs."),
    ("Spiders are not insects.",
     "Spiders are insects.",
     "Spiders have eight legs and two body parts; insects have six legs and three."),
    ("Sharks were around before there were trees.",
     "Trees were around long before there were sharks.",
     "Sharks go back about 450 million years; the first trees came later."),
    # --- science and space
    ("Sound travels faster through water than through air.",
     "Sound travels slower through water than through air.",
     "Water is denser and stiffer, so sound moves about four times faster."),
    ("A day on Venus is longer than its year.",
     "A day on Mars is longer than its year.",
     "Venus turns once every 243 Earth days but circles the Sun in about 225."),
    ("Bananas are botanically berries, but strawberries are not.",
     "Strawberries are botanically berries, but bananas are not.",
     "A true berry grows from one flower with one ovary; bananas qualify."),
    ("An adult human has 206 bones.",
     "An adult human has 306 bones.",
     "Babies have about 300, and many fuse together as they grow."),
    ("You cannot see the Great Wall of China from the Moon with the naked eye.",
     "Astronauts on the Moon can easily see the Great Wall of China.",
     "It is long but far too narrow to pick out from that distance."),
    ("Water expands when it freezes.",
     "Water shrinks when it freezes.",
     "Ice is about nine percent less dense, which is why it floats."),
    ("Lightning can strike the same place more than once.",
     "Lightning never strikes the same place twice.",
     "The Empire State Building is struck around twenty times a year."),
    ("Venus is the hottest planet in the solar system.",
     "Mercury is the hottest planet in the solar system.",
     "Venus's thick atmosphere traps heat even though Mercury is closer to the Sun."),
    ("Light from the Sun takes about eight minutes to reach Earth.",
     "Light from the Sun takes about eight seconds to reach Earth.",
     "The Sun is roughly 150 million kilometres away."),
    ("Mount Everest is still getting taller by a few millimetres each year.",
     "Mount Everest is still getting taller by several metres each year.",
     "The plates beneath the Himalayas keep pushing upward, very slowly."),
    ("Antarctica is the driest continent on Earth.",
     "Africa is the driest continent on Earth.",
     "Parts of Antarctica have had almost no rain or snow for millions of years."),
    ("Pluto was reclassified as a dwarf planet in 2006.",
     "Pluto was reclassified as a dwarf planet in 1996.",
     "The International Astronomical Union voted in 2006."),
    ("Diamonds are made of carbon.",
     "Diamonds are made of silicon.",
     "Carbon atoms squeezed under great heat and pressure form diamond."),
    ("Sound cannot travel through the vacuum of space.",
     "Sound travels through space, only more slowly than on Earth.",
     "Sound needs air or another material to carry it."),
    ("Astronauts grow slightly taller in space.",
     "Astronauts shrink slightly in space.",
     "With no gravity squashing the spine, it stretches by a few centimetres."),
    ("Saturn is less dense than water.",
     "Saturn is the densest planet in the solar system.",
     "In a bathtub big enough, Saturn would float."),
    ("The Moon is slowly drifting away from the Earth.",
     "The Moon is slowly drifting closer to the Earth.",
     "It moves away by about 3.8 centimetres every year."),
    ("A year on Mercury lasts about 88 Earth days.",
     "A year on Mercury lasts about 365 Earth days.",
     "Mercury is the closest planet to the Sun, so it races around it."),
    ("Jupiter's Great Red Spot is a giant storm.",
     "Jupiter's Great Red Spot is a giant volcano.",
     "It is a storm that has raged for hundreds of years."),
    ("Lightning is hotter than the surface of the Sun.",
     "Lightning is cooler than the surface of the Sun.",
     "A bolt reaches about 30,000 degrees; the Sun's surface is near 5,500."),
    # --- the body
    ("Your stomach grows a new lining every few days.",
     "Your stomach grows a new lining every few years.",
     "Stomach acid is strong enough that the lining has to be replaced constantly."),
    ("Babies are born without kneecaps.",
     "Babies are born without elbows.",
     "Their kneecaps start as soft cartilage and harden over a few years."),
    ("The smallest bone in the human body is in the ear.",
     "The smallest bone in the human body is in the finger.",
     "The stapes in the middle ear is about the size of a grain of rice."),
    ("Fingernails grow faster than toenails.",
     "Toenails grow faster than fingernails.",
     "Fingernails grow around three millimetres a month; toenails grow about a third of that."),
    ("A human heart beats around 100,000 times a day.",
     "A human heart beats around 10,000 times a day.",
     "At roughly 70 beats a minute that adds up quickly."),
    # --- world and places
    ("Russia spans eleven time zones.",
     "Russia spans seven time zones.",
     "It is so wide that the far east is nine hours ahead of Moscow."),
    ("Canada has the longest coastline of any country.",
     "Russia has the longest coastline of any country.",
     "Canada's countless islands add up to over 200,000 kilometres."),
    ("The Sahara is the largest hot desert in the world.",
     "The Gobi is the largest hot desert in the world.",
     "The Gobi is huge but cold; the Sahara is the biggest hot one."),
    ("The River Nile flows northward.",
     "The River Nile flows southward.",
     "It runs from central Africa up to the Mediterranean Sea."),
    ("Vatican City is the smallest country in the world.",
     "Monaco is the smallest country in the world.",
     "Vatican City covers less than half a square kilometre."),
    ("Australia is both a country and a continent.",
     "Greenland is both a country and a continent.",
     "Greenland is part of North America and belongs to Denmark."),
    ("Istanbul is a city on two continents.",
     "Cairo is a city on two continents.",
     "Istanbul sits on both sides of the Bosphorus, in Europe and Asia."),
    ("Mount Kilimanjaro is in Tanzania.",
     "Mount Kilimanjaro is in Kenya.",
     "It is Africa's highest mountain, just south of the Kenyan border."),
    ("The Dead Sea shore is the lowest land point on Earth.",
     "Death Valley is the lowest land point on Earth.",
     "The Dead Sea shore is over 400 metres below sea level."),
    ("Venice is built across more than a hundred small islands.",
     "Venice is built on one single island.",
     "Canals and bridges link roughly 118 islands."),
    ("Chess began in India.",
     "Chess began in China.",
     "Its ancestor chaturanga was played in India over 1,400 years ago."),
    ("The Taj Mahal took about twenty years to build.",
     "The Taj Mahal took about two years to build.",
     "Work ran from around 1632 to 1653."),
    ("Rajasthan is the largest Indian state by area.",
     "Maharashtra is the largest Indian state by area.",
     "Rajasthan covers roughly 342,000 square kilometres."),
    ("Hyderabad is famous as the City of Pearls.",
     "Hyderabad is famous as the City of Silk.",
     "It has been a major pearl trading centre for centuries."),
    ("India has the largest post office network in the world.",
     "China has the largest post office network in the world.",
     "India has well over 150,000 post offices."),
    ("India has won the 50-over Cricket World Cup twice.",
     "India has won the 50-over Cricket World Cup four times.",
     "The wins were in 1983 and 2011."),
    ("Sachin Tendulkar scored one hundred international centuries.",
     "Sachin Tendulkar scored seventy-five international centuries.",
     "He is the only player to reach one hundred."),
    # --- history
    ("Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
     "Cleopatra lived closer in time to the building of the Great Pyramid than to the Moon landing.",
     "The pyramid was built about 2,500 years before her; the Moon landing came about 2,000 years after."),
    ("Oxford University is older than the Aztec Empire.",
     "The Aztec Empire is older than Oxford University.",
     "Teaching at Oxford began in the 1090s; the Aztec empire grew in the 1400s."),
    ("The shortest war in history lasted under an hour.",
     "The shortest war in history lasted three days.",
     "The Anglo-Zanzibar War of 1896 ended in about 40 minutes."),
    ("Napoleon was about average height for a man of his time.",
     "Napoleon was only four feet tall.",
     "French measurements differed; he was around five foot six."),
    ("Mahatma Gandhi led the Dandi Salt March in 1930.",
     "Mahatma Gandhi led the Dandi Salt March in 1942.",
     "The 1942 movement was Quit India; the salt march came twelve years earlier."),
    ("India became a republic on the 26th of January 1950.",
     "India became a republic on the 15th of August 1947.",
     "The 15th of August 1947 was Independence Day."),
    ("The Eiffel Tower was built for the 1889 World's Fair.",
     "The Eiffel Tower was built for the 1900 Olympic Games.",
     "It marked a hundred years since the French Revolution."),
    ("Gutenberg's printing press arrived in the fifteenth century.",
     "Gutenberg's printing press arrived in the twelfth century.",
     "Gutenberg printed his famous Bible in the 1450s."),
    ("The Berlin Wall fell in 1989.",
     "The Berlin Wall fell in 1979.",
     "It came down on the ninth of November 1989."),
    ("The Wright brothers made the first powered flight in 1903.",
     "The Wright brothers made the first powered flight in 1913.",
     "Their first flight lasted twelve seconds."),
    ("Marie Curie won Nobel Prizes in two different sciences.",
     "Marie Curie won Nobel Prizes in three different sciences.",
     "She won in physics and in chemistry."),
    # --- food and everyday life
    ("Ketchup was once sold as a medicine.",
     "Ketchup was once used as money.",
     "In the 1830s a doctor sold tomato ketchup as a cure for indigestion."),
    ("Peanuts are legumes, not true nuts.",
     "Peanuts are true tree nuts.",
     "They grow underground and are related to beans and peas."),
    ("Chocolate can be poisonous to dogs.",
     "Chocolate is a perfectly safe treat for dogs.",
     "Dogs cannot process a chemical in chocolate called theobromine."),
    ("A cashew nut grows outside its fruit.",
     "A cashew nut grows inside its fruit.",
     "The nut hangs below the cashew apple."),
    ("Saffron is the most expensive spice in the world by weight.",
     "Cardamom is the most expensive spice in the world by weight.",
     "Each saffron crocus gives only three tiny threads."),
    ("Pizza Margherita is said to be named after Queen Margherita of Italy.",
     "Pizza Margherita is said to be named after the Margherita flower.",
     "The tale goes that a chef made it in 1889 in the colours of the Italian flag."),
    ("Carrots were originally purple or yellow, not orange.",
     "Carrots were originally bright red, not orange.",
     "Orange carrots were bred in the Netherlands in the 1600s."),
    ("Potatoes were first grown in the Andes mountains of South America.",
     "Potatoes were first grown in Ireland.",
     "Farmers in Peru were growing them thousands of years ago."),
    ("Coffee beans are the seeds of a fruit.",
     "Coffee beans are the roots of a shrub.",
     "They are the seeds inside the red coffee cherry."),
    ("About a quarter of an apple is air.",
     "About half of an apple is air.",
     "That trapped air is why apples float."),
    # --- tech and culture
    ("The first iPhone was released in 2007.",
     "The first iPhone was released in 2004.",
     "It went on sale in June 2007."),
    ("The first website went public in 1991.",
     "The first website went public in 1981.",
     "Tim Berners-Lee put it online at CERN."),
    ("Tetris was created in the Soviet Union.",
     "Tetris was created in Japan.",
     "Alexey Pajitnov wrote it in Moscow in 1984."),
    ("The word quarantine comes from a word meaning forty days.",
     "The word quarantine comes from a word meaning twenty days.",
     "Venetian ships once waited forty days before landing during plague outbreaks."),
    ("The name Bollywood blends Bombay and Hollywood.",
     "The name Bollywood blends Bengal and Hollywood.",
     "Bombay is now called Mumbai."),
]

# --- the host's tells -----------------------------------------------------
#
# hedge:       a sentence opener that sounds like backing away from the claim
# overexplain: a trailing justification nobody asked for
# repeat:      saying the key point again, a little too firmly
# stall:       a thinking-aloud opener that comes with a longer pause
# rushed:      no words are added; the line is simply delivered quickly

TELL_LABELS = {
    "hedge": "hedging",
    "overexplain": "over-explaining",
    "repeat": "saying it twice",
    "stall": "stalling",
    "rushed": "talking fast",
}

HEDGES = [
    "As far as anyone knows,",
    "I'm fairly certain that",
    "If I remember rightly,",
    "Honestly,",
    "Believe it or not,",
    "I'd say, more or less, that",
]

OVEREXPLAIN = [
    "And that is simply how it works, as anyone who has looked into it will tell you.",
    "It is very well documented, you can ask nearly anybody.",
    "There is nothing more to say about it, really, it is that straightforward.",
    "I did not make that up, so please do not look at me like that.",
]

REPEATS = [
    "Yes. Exactly that.",
    "That is right, that is what I said.",
    "Say it with me, that is the fact.",
]

STALLS = [
    "Let me think. Right.",
    "Hmm. Yes. Okay.",
    "Now, where do I start. Yes.",
]

#: Neutral lines the host uses when pressed. Tells are layered on top, the
#: same way as for the claim, so a calm defence can be a lie and a nervous
#: one can be the truth.
DEFENCES = [
    "You want proof? It holds up.",
    "I stand by what I said.",
    "Ask me again and I will say the same thing.",
    "That is the fact, and I am sticking to it.",
    "Why would I say it if it were not so?",
    "I have known this for years.",
    "I checked it just before the show.",
    "Go ahead, challenge me. I am not worried.",
]

OPENERS = [
    "Here is a fact for you.",
    "Listen closely.",
    "Write this one down.",
    "Here comes the next one.",
]
