import AVFoundation
import Foundation

/// Sound effects for the TV board.
///
/// The TV is the only device in the room with a speaker worth using -- the
/// phones are controllers held in someone's hand -- so all audio lives in
/// this target. Clips are generated by `tools/generate_sounds.py` and
/// bundled from `Resources/Sounds`.
@MainActor
final class SoundPlayer {

    static let shared = SoundPlayer()

    enum Effect: String {
        case rouletteClick = "roulette_click"
        case rouletteSpin  = "roulette_spin"
        /// The full game-win fanfare: bright ascending major arpeggio into
        /// a triumphant held chord with sparkle. Played wherever a TV game
        /// announces a winner (Roulette, Connect 4, Snakes & Ladders).
        /// Generated by `tools/generate_sounds.py`.
        case winFanfare    = "win_fanfare"
        /// A Connect 4 disc landing in its slot -- played by
        /// `TVConnect4BoardView` once a dropped disc's fall animation
        /// finishes. `winFanfare` above is reused for a Connect 4 win.
        case connect4Drop  = "connect4_drop"
        /// A snake striking: played by `TVSnakeLadderBoardView` when the
        /// snake's eat animation fires, just before the token slides down
        /// the body. Generated by `tools/generate_sounds.py`.
        case snakeBite     = "snake_bite"
        /// A dramatic descending doom sting: low percussive hits under a
        /// descending minor motif, dark and cinematic. Played layered with
        /// `snakeBite` by `TVSnakeLadderBoardView` when a snake bite
        /// cinematic fires -- the bite is the strike, this is the dread
        /// that follows the token down the body. Generated by
        /// `tools/generate_sounds.py`.
        case snakeDoomSting = "snake_doom_sting"
        /// A short ascending chime: played by `TVSnakeLadderBoardView` when
        /// a token starts climbing a ladder. Deliberately lighter than
        /// `winFanfare` so a ladder never reads as the game being over.
        case ladderClimb   = "ladder_climb"
        // Poker table (tools/generate_sounds.py): chips, a dealt card, a
        // knock for a check, a toss for a fold, the all-in shove, and a
        // quiet lounge loop that sits under the whole game.
        case pokerChips    = "poker_chips"
        case pokerCard     = "poker_card"
        case pokerCheck    = "poker_check"
        case pokerFold     = "poker_fold"
        case pokerAllIn    = "poker_allin"
        case pokerLounge   = "poker_lounge"
    }

    /// One reusable player per effect, plus a small pool for the click, which
    /// needs to overlap with itself as the ball speeds over the frets.
    private var players: [Effect: AVAudioPlayer] = [:]
    private var clickPool: [AVAudioPlayer] = []
    private var clickIndex = 0

    private init() {
        configureSession()
    }

    private func configureSession() {
        // .ambient so GameLab never stops whatever the room is already
        // playing; this is decoration, not the main event.
        let session = AVAudioSession.sharedInstance()
        try? session.setCategory(.ambient, mode: .default, options: [.mixWithOthers])
        try? session.setActive(true)
    }

    private func makePlayer(for effect: Effect) -> AVAudioPlayer? {
        guard let url = Bundle.main.url(forResource: effect.rawValue, withExtension: "wav"),
              let player = try? AVAudioPlayer(contentsOf: url)
        else { return nil }
        player.prepareToPlay()
        return player
    }

    private func player(for effect: Effect) -> AVAudioPlayer? {
        if let existing = players[effect] { return existing }
        let created = makePlayer(for: effect)
        players[effect] = created
        return created
    }

    /// Fire and forget. Restarts the clip if it is already playing.
    func play(_ effect: Effect, volume: Float = 1.0) {
        guard let player = player(for: effect) else { return }
        player.volume = volume
        player.currentTime = 0
        player.play()
    }

    /// The ball ticking over the frets fires faster than a single player can
    /// restart cleanly, so these round-robin through a small pool.
    func playClick(volume: Float = 1.0) {
        if clickPool.isEmpty {
            clickPool = (0..<4).compactMap { _ in makePlayer(for: .rouletteClick) }
        }
        guard !clickPool.isEmpty else { return }
        let player = clickPool[clickIndex % clickPool.count]
        clickIndex += 1
        player.volume = volume
        player.currentTime = 0
        player.play()
    }

    /// Starts the wheel loop, or does nothing if it is already running.
    func startLoop(_ effect: Effect, volume: Float = 0.5) {
        guard let player = player(for: effect) else { return }
        guard !player.isPlaying else { return }
        player.numberOfLoops = -1
        player.volume = volume
        player.currentTime = 0
        player.play()
    }

    func fadeOutLoop(_ effect: Effect, over seconds: TimeInterval = 0.6) {
        guard let player = players[effect], player.isPlaying else { return }
        player.setVolume(0, fadeDuration: seconds)
        Task { @MainActor in
            try? await Task.sleep(nanoseconds: UInt64(seconds * 1_000_000_000))
            player.stop()
            player.numberOfLoops = 0
        }
    }

    func stopAll() {
        players.values.forEach { $0.stop() }
        clickPool.forEach { $0.stop() }
    }
}
