import Foundation

// MARK: - Hot Potato categories
//
// 120 bundled categories, easy enough that anyone can name a few under
// pressure. Fresh AI categories (kind "hotpotato") are merged in when
// the server is reachable.

enum HotPotatoDeck {
    static let categories: [String] = [
        "Things you find in a kitchen",
        "Fruits",
        "Vegetables",
        "Animals that live in water",
        "Animals with four legs",
        "Birds",
        "Insects and bugs",
        "Things that are red",
        "Things that are yellow",
        "Things that are round",
        "Things that are cold",
        "Things that are hot",
        "Things that are sticky",
        "Things that make noise",
        "Things that fly",
        "Things with wheels",
        "Things with buttons",
        "Things you plug in",
        "Things you wear on your feet",
        "Things you wear on your head",
        "Things in a school bag",
        "Things in a bathroom",
        "Things in a bedroom",
        "Things in a garden",
        "Things in a hospital",
        "Things at a wedding",
        "Things at a birthday party",
        "Things at the beach",
        "Things in the sky",
        "Things in space",
        "Things you can open",
        "Things you can fold",
        "Things you can throw",
        "Things you can climb",
        "Things that break easily",
        "Things that grow",
        "Things made of wood",
        "Things made of metal",
        "Things made of paper",
        "Things made of glass",
        "Kinds of sweets",
        "Breakfast foods",
        "Street foods",
        "Pizza toppings",
        "Ice cream flavours",
        "Drinks",
        "Spices",
        "Snacks",
        "Kinds of bread",
        "Desserts",
        "Countries",
        "Capital cities",
        "Cities in India",
        "Rivers",
        "Famous buildings and monuments",
        "Planets and stars",
        "Languages",
        "Sports",
        "Things in a cricket match",
        "Football teams",
        "Olympic events",
        "Board and card games",
        "Video games",
        "Cartoon characters",
        "Superheroes",
        "Disney films",
        "Animated films",
        "Famous singers",
        "Famous actors",
        "Famous cricketers",
        "Musical instruments",
        "Dance styles",
        "Song titles",
        "TV shows",
        "Jobs",
        "Things a doctor uses",
        "Things a chef uses",
        "Tools",
        "School subjects",
        "Things a teacher says",
        "Things your mum says",
        "Excuses for being late",
        "Reasons to celebrate",
        "Things that make you happy",
        "Things people are scared of",
        "Things you say on the phone",
        "Apps on a phone",
        "Brands",
        "Car brands",
        "Ways to travel",
        "Things at an airport",
        "Things at a railway station",
        "Things in a supermarket",
        "Things you buy at a market",
        "Shops",
        "Colours",
        "Shapes",
        "Body parts",
        "Clothes",
        "Things in a wallet or purse",
        "Weather words",
        "Things to do on a rainy day",
        "Things to do in summer",
        "Festivals",
        "Holiday destinations",
        "Things that are soft",
        "Things that are tiny",
        "Things that are huge",
        "Things that smell good",
        "Things that smell bad",
        "Words that rhyme with cat",
        "Words that start with S",
        "Words that start with B",
        "Words that end in -ing",
        "Names that start with A",
        "Boys' names",
        "Girls' names",
        "Famous scientists and inventors",
        "Fairy tales",
        "Pets",
    ]
}
