import Foundation

// MARK: - Word of the Day list, part one

extension WordDayList {
    static let partOne: [WordDayEntry] = [
        entry("serendipity", "noun",
              "Finding something good or useful by happy accident.",
              "It was pure serendipity that I sat next to my oldest friend on the train.",
              "Coined in 1754 by Horace Walpole from a Persian fairy tale, The Three Princes of Serendip. Serendip is an old name for Sri Lanka."),
        entry("petrichor", "noun",
              "The earthy smell in the air when rain falls on dry ground.",
              "After weeks of heat, the first shower filled the street with petrichor.",
              "Made up in 1964 by two Australian scientists from Greek petra, stone, and ichor, the golden fluid said to flow in the veins of the gods."),
        entry("mellifluous", "adjective",
              "Sweet, smooth and pleasant to hear.",
              "The radio host had a mellifluous voice that made the traffic news sound like poetry.",
              "From Latin mel, honey, and fluere, to flow: a voice that flows like honey."),
        entry("ephemeral", "adjective",
              "Lasting for a very short time.",
              "Soap bubbles are beautiful but ephemeral.",
              "From Greek ephemeros, lasting only a day. Mayflies belong to the insect order Ephemeroptera because adults live for about a day."),
        entry("quixotic", "adjective",
              "Hopeful and idealistic in a way that is not practical.",
              "His quixotic plan was to clean the whole beach by himself before lunch.",
              "From Don Quixote, the dreamy hero of Cervantes's novel, who charged at windmills thinking they were giants."),
        entry("defenestration", "noun",
              "The act of throwing someone or something out of a window.",
              "The defenestration of my old phone was not my finest moment.",
              "From Latin de, out of, and fenestra, window. It became famous after the Defenestration of Prague in 1618, when officials were thrown from a castle window and survived."),
        entry("gobbledygook", "noun",
              "Language that is long-winded and hard to understand.",
              "The instructions were pure gobbledygook, so we guessed instead.",
              "Coined in 1944 by American congressman Maury Maverick, who said official jargon sounded like a turkey gobbling."),
        entry("maverick", "noun",
              "An independent person who does things their own way.",
              "She was a maverick who started her own company at nineteen.",
              "From Samuel Maverick, a Texas rancher of the 1800s who did not brand his calves, so unbranded cattle were called mavericks."),
        entry("nostalgia", "noun",
              "A warm, wistful longing for the past.",
              "The old cartoon theme song filled us all with nostalgia.",
              "Coined in 1688 by Swiss medical student Johannes Hofer from Greek nostos, homecoming, and algos, pain. It first described homesick soldiers."),
        entry("ubiquitous", "adjective",
              "Seeming to be everywhere at once.",
              "Phones are so ubiquitous that it is hard to find a photo without one in it.",
              "From Latin ubique, everywhere."),
        entry("loquacious", "adjective",
              "Very talkative.",
              "Our loquacious taxi driver told us his whole life story in ten minutes.",
              "From Latin loqui, to speak, the same root as eloquent and ventriloquist."),
        entry("sesquipedalian", "adjective",
              "Using long words, or being a long word.",
              "The professor's sesquipedalian speech sent half the class to the dictionary.",
              "From Latin sesquipedalis, a foot and a half long. The Roman poet Horace joked about words a foot and a half long."),
        entry("lackadaisical", "adjective",
              "Lacking enthusiasm and effort.",
              "His lackadaisical attempt at cleaning left more dust than before.",
              "From the old sigh lackaday, short for alack the day, a way of saying how sad."),
        entry("kerfuffle", "noun",
              "A noisy fuss or commotion.",
              "There was a kerfuffle at the counter when two people grabbed the last samosa.",
              "From the Scottish word carfuffle, to throw into disorder."),
        entry("discombobulate", "verb",
              "To confuse or upset someone.",
              "The surprise party completely discombobulated my grandfather.",
              "A playful American invention of the 1830s, a mock-fancy twist on words like discompose and discomfit."),
        entry("flabbergasted", "adjective",
              "Extremely surprised.",
              "I was flabbergasted when my little brother cleaned his room without being asked.",
              "English slang from the 1770s, possibly a mash of flabby and aghast."),
        entry("bamboozle", "verb",
              "To trick or confuse someone.",
              "The magician bamboozled the whole audience with a single coin.",
              "It appeared around 1700 from nowhere anyone can trace. The writer Jonathan Swift complained about it as annoying new slang."),
        entry("hullabaloo", "noun",
              "A noisy uproar.",
              "The hullabaloo at the cricket ground could be heard three streets away.",
              "From the 1700s, built from shouts like hallo and hullo repeated with a rhyme."),
        entry("nincompoop", "noun",
              "A foolish or silly person.",
              "Only a nincompoop would wear socks with sandals in the rain, said my sister, wearing socks with sandals.",
              "Recorded from the 1670s; nobody knows where it came from, though many have guessed."),
        entry("cacophony", "noun",
              "A harsh, jarring mix of sounds.",
              "Twenty children with new whistles made a cacophony.",
              "From Greek kakos, bad, and phone, sound."),
        entry("euphoria", "noun",
              "A feeling of intense happiness and excitement.",
              "There was pure euphoria when the last-ball six won the match.",
              "From Greek euphoros, bearing well, from eu, good, and pherein, to carry."),
        entry("resilient", "adjective",
              "Able to recover quickly from difficulty.",
              "The resilient little plant grew back after every storm.",
              "From Latin resilire, to leap back."),
        entry("wanderlust", "noun",
              "A strong desire to travel and explore.",
              "One look at the mountain photos and her wanderlust kicked in.",
              "From German wandern, to hike, and Lust, desire."),
        entry("schadenfreude", "noun",
              "Pleasure felt at someone else's small misfortune.",
              "I felt a little schadenfreude when the boastful player tripped over the ball.",
              "From German Schaden, harm, and Freude, joy."),
        entry("zeitgeist", "noun",
              "The general mood or spirit of a particular time.",
              "That song perfectly captured the zeitgeist of the summer.",
              "From German Zeit, time, and Geist, spirit."),
        entry("doppelganger", "noun",
              "Someone who looks exactly like someone else.",
              "I saw your doppelganger at the market and waved at a stranger.",
              "From German Doppelganger, double-goer. In folklore, meeting your double was a bad omen."),
        entry("juggernaut", "noun",
              "A huge, powerful force that seems impossible to stop.",
              "The team was a juggernaut, winning every match of the season.",
              "From Jagannath, the deity of the temple at Puri in Odisha, whose enormous chariots are pulled through the streets during the Rath Yatra festival."),
        entry("bungalow", "noun",
              "A house with only one storey.",
              "My grandparents live in a cosy bungalow with a mango tree outside.",
              "From Hindi bangla, meaning in the style of Bengal, after the single-storey thatched houses of the region."),
        entry("shampoo", "noun",
              "A liquid soap for washing hair.",
              "The new shampoo smelled so strongly of coconut that the dog followed me around.",
              "From Hindi champo, to press or knead, as in a head massage. Sake Dean Mahomed opened a shampooing bath house in Brighton in 1814."),
        entry("pyjamas", "noun",
              "Loose clothes worn for sleeping.",
              "We had a movie night in our pyjamas.",
              "From Persian and Urdu pai, leg, and jama, garment: leg clothing."),
        entry("cushy", "adjective",
              "Easy and comfortable.",
              "He got the cushy job of taste-testing the desserts.",
              "Picked up by British soldiers in India from Hindi and Urdu khush, pleasant or happy."),
        entry("dungarees", "noun",
              "Trousers with a bib and straps over the shoulders.",
              "She painted the fence in her old dungarees.",
              "From Dongri, a neighbourhood of Mumbai where a thick, cheap cotton cloth was made."),
        entry("avatar", "noun",
              "A picture or character that represents a person online, or a form something takes.",
              "My avatar in the game is a penguin wearing sunglasses.",
              "From Sanskrit avatara, descent, used for the forms a god takes when coming down to earth."),
        entry("guru", "noun",
              "A wise teacher or an expert.",
              "My aunt is the family's cooking guru.",
              "From Sanskrit guru, meaning heavy or weighty, as in someone of great importance."),
        entry("jungle", "noun",
              "A thick tropical forest, or any wild, confusing place.",
              "My bedroom became a jungle of laundry by Friday.",
              "From Hindi jangal, from Sanskrit jangala, which meant dry, uncultivated land, not forest at all."),
        entry("mantra", "noun",
              "A word or phrase repeated often, especially for focus or encouragement.",
              "Her mantra before every exam is simple: one question at a time.",
              "From Sanskrit, an instrument of thought: man, to think, and tra, a tool."),
        entry("cheetah", "noun",
              "A large spotted wild cat, the fastest land animal.",
              "A cheetah can go from standing still to motorway speed in about three seconds.",
              "From Hindi chita, from Sanskrit chitraka, meaning speckled."),
        entry("catamaran", "noun",
              "A boat with two parallel hulls.",
              "We sailed to the island on a bright yellow catamaran.",
              "From Tamil kattumaram, tied wood, the fishing rafts of logs lashed together on the southern coast."),
        entry("mango", "noun",
              "A sweet tropical fruit with orange flesh.",
              "Summer at our house means mango juice on every chin.",
              "From Tamil mankay through Malayalam, then Portuguese traders, who spread the word worldwide."),
        entry("pundit", "noun",
              "An expert who gives opinions, especially in the media.",
              "The cricket pundits all predicted the wrong winner.",
              "From Sanskrit pandita, a learned person or scholar."),
        entry("bandana", "noun",
              "A large patterned scarf worn on the head or neck.",
              "He tied a red bandana round his head for the hike.",
              "From Hindi bandhna, to tie, after the tie-dyed cloth made in India."),
        entry("robot", "noun",
              "A machine that can carry out tasks automatically.",
              "Our robot vacuum spends most of its time stuck under the sofa.",
              "From Czech robota, forced labour. It entered English through Karel Capek's 1920 play R.U.R., about artificial workers."),
        entry("quarantine", "noun",
              "A period of keeping people or animals apart to stop disease spreading.",
              "The new puppy spent a week in quarantine before coming home.",
              "From Italian quaranta giorni, forty days, the time ships had to wait off Venice before landing during plague outbreaks."),
        entry("salary", "noun",
              "A fixed regular payment for work.",
              "Her first salary went straight into buying her parents a gift.",
              "From Latin salarium, linked to sal, salt. The popular story that Roman soldiers were paid in salt is probably a legend."),
        entry("clue", "noun",
              "A piece of information that helps solve a problem.",
              "The muddy footprints were the clue that solved the mystery of the missing cake.",
              "From clew, a ball of thread. In Greek myth, Theseus used a thread to find his way out of the Minotaur's maze."),
        entry("muscle", "noun",
              "Body tissue that contracts to produce movement.",
              "Carrying all the shopping bags gave my arms a proper muscle workout.",
              "From Latin musculus, little mouse, because a rippling muscle was thought to look like a mouse moving under the skin."),
        entry("nightmare", "noun",
              "A frightening dream, or a very unpleasant experience.",
              "Getting forty people into one photo was a nightmare.",
              "The mare here is not a horse but an old word for a spirit believed to sit on sleepers' chests and give them bad dreams."),
        entry("disaster", "noun",
              "A sudden event causing great damage or trouble.",
              "My first attempt at a souffle was a delicious disaster.",
              "From Italian disastro, ill-starred: dis, bad, and astro, star. Bad luck was once blamed on the stars."),
        entry("window", "noun",
              "An opening in a wall to let in light and air.",
              "The cat sat in the window all afternoon watching birds.",
              "From Old Norse vindauga, wind eye: a hole in the roof or wall that let out smoke and let in wind."),
        entry("algebra", "noun",
              "The branch of maths that uses letters to stand for numbers.",
              "Algebra suddenly made sense when the teacher explained it with pizza slices.",
              "From Arabic al-jabr, the reunion of broken parts, from the title of a 9th-century book by the mathematician al-Khwarizmi."),
        entry("algorithm", "noun",
              "A set of step-by-step rules for solving a problem.",
              "The app's algorithm decided I really, really like cat videos.",
              "From the name of al-Khwarizmi, a 9th-century Persian mathematician working in Baghdad, whose name was written in Latin as Algoritmi."),
        entry("zero", "noun",
              "The number 0; nothing at all.",
              "The score was zero all at half time.",
              "From Arabic sifr, empty, which translated Sanskrit shunya. Indian mathematicians were among the first to treat zero as a number."),
        entry("sugar", "noun",
              "A sweet substance made from cane or beet.",
              "Grandma's tea has three spoons of sugar and no apology.",
              "From Sanskrit sharkara, meaning gravel or grit, through Persian, Arabic and Italian."),
        entry("orange", "noun",
              "A round citrus fruit, or the colour of that fruit.",
              "She peeled the orange in one long, perfect spiral.",
              "From Sanskrit naranga through Persian narang. In English, a norange slowly became an orange."),
        entry("apron", "noun",
              "A garment worn over the front of clothes to keep them clean.",
              "Dad wore his flowery apron to make breakfast.",
              "Originally a napron. People heard a napron as an apron, and the n jumped across."),
        entry("umpire", "noun",
              "An official who watches a game and makes sure the rules are followed.",
              "The umpire raised his finger and the whole stadium groaned.",
              "From Old French nonper, not equal, meaning a neutral third person. A noumpere became an umpire."),
        entry("nickname", "noun",
              "A familiar or funny name used instead of a real name.",
              "His nickname is Rocket because he is always the last to arrive.",
              "From an ekename, an extra name. People heard it as a nekename, and nickname was born."),
        entry("goodbye", "exclamation",
              "A word said when leaving.",
              "We said goodbye at the station and waved until the train was gone.",
              "A shortening of God be with ye, squeezed together over centuries."),
        entry("nerd", "noun",
              "A person who is very enthusiastic about a particular subject.",
              "I am a total nerd about trains and I am proud of it.",
              "First seen in print in Dr Seuss's 1950 book If I Ran the Zoo, as the name of an odd little creature."),
        entry("chortle", "verb",
              "To laugh in a breathy, gleeful way.",
              "Grandpa chortled at his own joke before he even reached the end.",
              "Invented by Lewis Carroll in Through the Looking-Glass (1871), probably a blend of chuckle and snort."),
        entry("galumph", "verb",
              "To move in a clumsy, noisy way.",
              "The puppy galumphed across the garden to greet us.",
              "Invented by Lewis Carroll in his nonsense poem Jabberwocky, perhaps from gallop and triumph."),
        entry("pandemonium", "noun",
              "Wild and noisy disorder.",
              "When the power came back on, pandemonium broke out as everyone rushed to the TV.",
              "Coined by John Milton in Paradise Lost (1667) as the name of the capital of Hell: Greek pan, all, and daimon, spirit."),
        entry("utopia", "noun",
              "An imagined perfect place.",
              "A library with a snack bar would be my idea of utopia.",
              "Coined by Thomas More in 1516 for an ideal island. It comes from Greek ou, not, and topos, place: a place that does not exist."),
        entry("gargantuan", "adjective",
              "Enormous.",
              "He ordered a gargantuan ice cream sundae and finished every bite.",
              "From Gargantua, a giant with a huge appetite in the 16th-century stories of French writer Rabelais."),
        entry("lilliputian", "adjective",
              "Very small.",
              "The doll's house had lilliputian teacups the size of peas.",
              "From Lilliput, the island of tiny people in Jonathan Swift's Gulliver's Travels (1726)."),
        entry("malapropism", "noun",
              "The mistaken use of a word that sounds like the right one, often to funny effect.",
              "Saying the dog was a pigeon of good behaviour was a classic malapropism.",
              "From Mrs Malaprop, a character in Sheridan's 1775 play The Rivals, who constantly mixed up words. Her name comes from French mal a propos, inappropriate."),
        entry("boycott", "verb",
              "To refuse to buy, use or take part in something as a protest.",
              "The students boycotted the canteen until it brought back samosas.",
              "From Captain Charles Boycott, an Irish land agent whom the whole community refused to deal with in 1880."),
        entry("silhouette", "noun",
              "The dark outline of something against a lighter background.",
              "We saw the silhouette of a camel against the setting sun.",
              "Named after Etienne de Silhouette, a French finance minister in 1759 famous for cutting costs. Cheap cut-paper portraits were mockingly named after him."),
        entry("cardigan", "noun",
              "A knitted jumper that fastens at the front.",
              "Grandma always has a spare cardigan in case anyone gets cold.",
              "Named after the 7th Earl of Cardigan, a British commander in the Crimean War who wore this kind of knitted waistcoat."),
        entry("sandwich", "noun",
              "Two slices of bread with a filling between them.",
              "I made a sandwich so tall it needed a toothpick to stand up.",
              "Named after the 4th Earl of Sandwich, who is said to have eaten meat between bread so he would not have to leave his game or his desk."),
        entry("leotard", "noun",
              "A tight one-piece garment worn by dancers and gymnasts.",
              "She practised her cartwheels in a sparkly blue leotard.",
              "Named after Jules Leotard, a 19th-century French acrobat who invented the flying trapeze act."),
        entry("saxophone", "noun",
              "A brass musical instrument played with a reed.",
              "The jazz band's saxophone solo got the whole room dancing.",
              "Named after Adolphe Sax, the Belgian instrument maker who invented it in the 1840s."),
        entry("jumbo", "adjective",
              "Very large.",
              "We shared a jumbo box of popcorn at the cinema.",
              "From Jumbo, a famous giant African elephant at London Zoo who was later sold to the American showman P. T. Barnum in 1882."),
        entry("marathon", "noun",
              "A running race of about 42 kilometres, or any long, tiring task.",
              "Cleaning the garage turned into a weekend-long marathon.",
              "From the Greek town of Marathon. Legend says a messenger ran from there to Athens to announce a victory in 490 BC."),
        entry("tantalise", "verb",
              "To tease someone with something they want but cannot have.",
              "The smell of biryani tantalised us for an hour before dinner was ready.",
              "From Tantalus, a king in Greek myth punished by standing in water under fruit trees, with both always just out of reach."),
        entry("echo", "noun",
              "A sound that bounces back off a surface.",
              "We shouted our names into the cave and the echo shouted back.",
              "From Echo, a nymph in Greek myth who could only repeat the last words spoken to her."),
        entry("panic", "noun",
              "Sudden, overwhelming fear.",
              "There was a moment of panic when I could not find my passport.",
              "From the Greek god Pan, whose sudden shouts in lonely places were said to fill travellers with terror."),
        entry("cereal", "noun",
              "A grain such as wheat or rice, or a breakfast food made from grain.",
              "My little sister counts every piece of cereal in her bowl.",
              "From Ceres, the Roman goddess of grain and farming."),
        entry("volcano", "noun",
              "A mountain with a crater through which lava and gas erupt.",
              "We watched a documentary about a volcano that grew in a farmer's field.",
              "From Vulcano, an island near Sicily named after Vulcan, the Roman god of fire."),
        entry("mentor", "noun",
              "An experienced person who guides someone less experienced.",
              "My first coach became my mentor for life.",
              "From Mentor, a character in Homer's Odyssey who guided Odysseus's son. The goddess Athena sometimes took his form."),
        entry("odyssey", "noun",
              "A long and eventful journey.",
              "Getting home in the storm turned into a four-hour odyssey.",
              "From the Odyssey, Homer's epic poem about Odysseus's ten-year voyage home after the Trojan War."),
        entry("nemesis", "noun",
              "A long-standing rival or an unbeatable opponent.",
              "The neighbour's cat is my dog's nemesis.",
              "From Nemesis, the Greek goddess who punished pride and arrogance."),
        entry("atlas", "noun",
              "A book of maps.",
              "We spread the atlas on the floor and planned an imaginary world tour.",
              "From the Titan Atlas, who held up the sky in Greek myth. Mapmaker Gerardus Mercator used his name for a book of maps in the 1590s."),
        entry("jovial", "adjective",
              "Cheerful and friendly.",
              "The jovial shopkeeper gave every child a free sweet.",
              "From Jove, another name for Jupiter. People born under the planet Jupiter were believed to be cheerful."),
        entry("mercurial", "adjective",
              "Changing mood or mind quickly and unpredictably.",
              "The weather in the hills is mercurial: sunshine, then hail, then sunshine.",
              "From Mercury, the quick-moving messenger god, and the planet that moves fastest across the sky."),
        entry("tycoon", "noun",
              "A wealthy, powerful businessperson.",
              "He went from selling lemonade to being a juice tycoon.",
              "From Japanese taikun, great lord, a title used for the shogun when speaking to foreigners."),
        entry("tsunami", "noun",
              "A huge sea wave caused by an earthquake or volcano.",
              "The village built a tall wall to protect it from a tsunami.",
              "From Japanese tsu, harbour, and nami, wave."),
        entry("karaoke", "noun",
              "Singing along to recorded music, usually with the words on a screen.",
              "Karaoke night revealed that our quietest cousin is a rock star.",
              "From Japanese kara, empty, and oke, short for okesutora, orchestra: an orchestra with no singer."),
        entry("ketchup", "noun",
              "A thick tomato sauce.",
              "He puts ketchup on everything, even on noodles.",
              "Probably from Hokkien Chinese ke-tsiap, a fish sauce. Tomatoes were only added centuries later."),
        entry("kowtow", "verb",
              "To be too eager to please someone in authority.",
              "He refused to kowtow to the bossy club captain.",
              "From Chinese ketou, knock the head: kneeling so low that the forehead touches the ground."),
        entry("kangaroo", "noun",
              "An Australian animal that hops on strong back legs and carries its young in a pouch.",
              "The baby kangaroo peeked out of the pouch and ducked back in.",
              "From gangurru, a word in the Guugu Yimithirr language, recorded by Captain Cook's crew in 1770."),
        entry("boomerang", "noun",
              "A curved throwing stick that can return to the thrower.",
              "My first boomerang throw landed in the neighbour's garden and stayed there.",
              "From the Dharug language of the Sydney area in Australia."),
        entry("chocolate", "noun",
              "A sweet food made from roasted cacao seeds.",
              "There is always room for one more piece of chocolate.",
              "From Nahuatl, the Aztec language, through Spanish. The Aztecs drank it as a bitter, frothy drink."),
        entry("tomato", "noun",
              "A soft red fruit used as a vegetable.",
              "Our balcony plant grew one proud tomato all summer.",
              "From Nahuatl tomatl, through Spanish tomate."),
        entry("avocado", "noun",
              "A pear-shaped fruit with creamy green flesh and a large stone.",
              "She mashed an avocado onto toast and called it breakfast.",
              "From Nahuatl ahuacatl, through Spanish."),
        entry("barbecue", "noun",
              "A meal cooked outdoors over an open fire or grill.",
              "The barbecue smoke drifted over three gardens.",
              "From Taino barbacoa, a wooden frame for cooking or sleeping on, through Spanish."),
        entry("canoe", "noun",
              "A narrow, light boat moved with paddles.",
              "We paddled the canoe in circles until we worked out how to steer.",
              "From Taino canoa, through Spanish. It was one of the first words Columbus brought back from the Caribbean."),
        entry("hammock", "noun",
              "A hanging bed of fabric or netting.",
              "He spent the holiday reading in a hammock between two palm trees.",
              "From Taino hamaca, through Spanish."),
        entry("hurricane", "noun",
              "A violent tropical storm with very strong winds.",
              "The hurricane turned the sky a strange shade of green.",
              "From Taino hurakan, through Spanish huracan."),
        entry("safari", "noun",
              "A journey to see wild animals in their natural home.",
              "On safari we saw a lion yawn, which was somehow terrifying.",
              "From Swahili safari, journey, which came from Arabic safar."),
        entry("bazaar", "noun",
              "A market of small shops and stalls.",
              "We got lost in the bazaar and found the best sweets of the trip.",
              "From Persian bazar, market."),
        entry("caravan", "noun",
              "A group of travellers journeying together, or a home on wheels.",
              "A caravan of camels crossed the dunes at sunset.",
              "From Persian karwan, a company of desert travellers."),
        entry("paradise", "noun",
              "An ideal or perfect place.",
              "For my dog, a beach with no lead is paradise.",
              "From Old Persian pairidaeza, a walled garden or park."),
        entry("checkmate", "noun",
              "The winning position in chess, when the king cannot escape.",
              "My grandmother said checkmate with a very small smile.",
              "From Persian shah mat, the king is helpless."),
        entry("magazine", "noun",
              "A regular publication with articles and pictures.",
              "The dentist's waiting room had magazines from ten years ago.",
              "From Arabic makhazin, storehouses. A magazine was first a storehouse, then a storehouse of information."),
        entry("giraffe", "noun",
              "A tall African animal with a very long neck.",
              "The giraffe stole a leaf from the tallest tree with no effort at all.",
              "From Arabic zarafa, through Italian."),
        entry("admiral", "noun",
              "A very senior officer in the navy.",
              "My toy boat has an admiral made of a peg.",
              "From Arabic amir al-, commander of, as in amir al-bahr, commander of the sea."),
        entry("alligator", "noun",
              "A large reptile like a crocodile with a broad snout.",
              "The alligator lay so still that we thought it was a log.",
              "From Spanish el lagarto, the lizard."),
        entry("mosquito", "noun",
              "A small flying insect that bites.",
              "One mosquito kept the whole room awake.",
              "From Spanish and Portuguese mosquito, little fly."),
        entry("vanilla", "noun",
              "A flavouring from the pods of a tropical orchid.",
              "Vanilla is the most popular flavour, and also the most underrated.",
              "From Spanish vainilla, little pod."),
        entry("tornado", "noun",
              "A violently spinning column of air.",
              "The tornado lifted a trampoline and set it down two streets away.",
              "From Spanish tronada, thunderstorm, mixed with tornar, to turn."),
        entry("ballot", "noun",
              "A secret vote, or the paper used to vote.",
              "The class held a ballot to choose the name of the hamster.",
              "From Italian ballotta, a little ball. In Venice, votes were cast by dropping small balls into a box."),
        entry("umbrella", "noun",
              "A folding canopy on a stick that protects from rain or sun.",
              "The wind turned my umbrella inside out on the first day of the monsoon.",
              "From Italian ombrella, from Latin umbra, shade. It was first a sunshade."),
        entry("piano", "noun",
              "A large keyboard instrument with hammers that strike strings.",
              "He can play only one song on the piano, but he plays it everywhere.",
              "Short for pianoforte, Italian for soft-loud, because it could play both, unlike the harpsichord."),
        entry("bankrupt", "adjective",
              "Unable to pay debts.",
              "After the fair, my piggy bank was officially bankrupt.",
              "From Italian banca rotta, broken bench. A moneylender who could not pay had his bench broken, so the story goes."),
        entry("fiasco", "noun",
              "A complete and embarrassing failure.",
              "The school play was a fiasco when the set fell over, but everyone loved it.",
              "Italian for flask or bottle. Far fiasco, to make a bottle, was Italian theatre slang for a flop; nobody is sure why."),
        entry("confetti", "noun",
              "Small pieces of coloured paper thrown at celebrations.",
              "We were still finding confetti in our hair a week after the wedding.",
              "Italian for sweets. At carnivals, people threw sugared almonds, later replaced by paper."),
    ]
}
