import Foundation

// MARK: - Word of the Day list, part two

extension WordDayList {
    static let partTwo: [WordDayEntry] = [
        entry("trivia", "noun",
              "Small, unimportant facts.",
              "My uncle knows trivia about every cricket match since 1983.",
              "From Latin trivium, a place where three roads meet. Talk at the crossroads was thought to be everyday chatter."),
        entry("companion", "noun",
              "A person you spend time with or travel with.",
              "My dog is my favourite walking companion.",
              "From Latin com, with, and panis, bread: someone you share your bread with."),
        entry("candidate", "noun",
              "A person applying for a job or standing for election.",
              "Each candidate gave a speech promising longer lunch breaks.",
              "From Latin candidatus, dressed in white. Romans seeking office wore togas whitened with chalk."),
        entry("ambition", "noun",
              "A strong desire to achieve something.",
              "Her ambition is to visit every continent before she turns thirty.",
              "From Latin ambitio, going around, because Roman politicians went around asking for votes."),
        entry("sinister", "adjective",
              "Seeming evil or threatening.",
              "The empty house had a sinister creak on the stairs.",
              "Latin for left. The left side was once thought unlucky."),
        entry("dexterity", "noun",
              "Skill in using the hands.",
              "The juggler's dexterity left us speechless.",
              "From Latin dexter, on the right side, because most people's right hand is their skilful one."),
        entry("rival", "noun",
              "Someone competing with another for the same thing.",
              "The two bakeries on our street are friendly rivals.",
              "From Latin rivalis, a person using the same stream, from rivus, stream. Neighbours sharing water often quarrelled."),
        entry("pupil", "noun",
              "The dark circle in the centre of the eye; also a student.",
              "Your pupils get bigger in the dark to let in more light.",
              "From Latin pupilla, little doll, because you can see a tiny reflection of yourself in someone else's eye."),
        entry("vaccine", "noun",
              "A substance that trains the body to fight a disease.",
              "The nurse gave the vaccine so quickly that I barely noticed.",
              "From Latin vacca, cow. Edward Jenner used material from cowpox in 1796 to protect people from smallpox."),
        entry("calculate", "verb",
              "To work out using numbers.",
              "We calculated that we had eaten forty idlis between six of us.",
              "From Latin calculus, a small pebble. Romans counted using pebbles on a board."),
        entry("investigate", "verb",
              "To look into something carefully to find the truth.",
              "We investigated the mystery of the missing remote and found it in the fridge.",
              "From Latin vestigium, footprint or track: following the footprints."),
        entry("sarcasm", "noun",
              "Saying the opposite of what you mean to mock or tease.",
              "Oh great, more rain, she said, with heavy sarcasm.",
              "From Greek sarkazein, to tear flesh like a dog."),
        entry("school", "noun",
              "A place where children are taught.",
              "The first day of school always smells of new pencils.",
              "From Greek schole, which meant leisure. Using free time for discussion and learning was a luxury."),
        entry("enthusiasm", "noun",
              "Eager enjoyment and interest.",
              "The puppy greeted every visitor with total enthusiasm.",
              "From Greek entheos, having a god inside you."),
        entry("dinosaur", "noun",
              "A prehistoric reptile, many of them enormous.",
              "My nephew can name forty dinosaurs but not his own street.",
              "Coined in 1842 by British scientist Richard Owen from Greek deinos, terrible, and sauros, lizard."),
        entry("hippopotamus", "noun",
              "A large African animal that spends much of its day in water.",
              "A hippopotamus can hold its breath for about five minutes.",
              "From Greek hippos, horse, and potamos, river: river horse."),
        entry("octopus", "noun",
              "A sea creature with eight arms.",
              "The octopus squeezed through a gap the size of a coin.",
              "From Greek okto, eight, and pous, foot."),
        entry("rhinoceros", "noun",
              "A large thick-skinned animal with one or two horns on its nose.",
              "The rhinoceros looked grumpy but was only eating grass.",
              "From Greek rhis, nose, and keras, horn."),
        entry("astronaut", "noun",
              "A person trained to travel in space.",
              "The astronaut floated a strawberry across the space station.",
              "From Greek astron, star, and nautes, sailor: star sailor."),
        entry("telephone", "noun",
              "A device for talking to someone far away.",
              "Grandpa still answers the telephone as if it might be the king.",
              "From Greek tele, far, and phone, voice."),
        entry("photograph", "noun",
              "A picture taken with a camera.",
              "We framed the photograph of the whole family pulling silly faces.",
              "From Greek phos, light, and graphe, writing: writing with light. Sir John Herschel popularised the word in 1839."),
        entry("alphabet", "noun",
              "The set of letters used to write a language.",
              "My little cousin sings the alphabet song at full volume.",
              "From alpha and beta, the first two letters of the Greek alphabet."),
        entry("eureka", "exclamation",
              "A cry of joy at a sudden discovery.",
              "Eureka, I found the other sock!",
              "Greek for I have found it. Archimedes supposedly shouted it in the bath when he worked out how to measure volume."),
        entry("laconic", "adjective",
              "Using very few words.",
              "His laconic reply to the long message was just: ok.",
              "From Laconia, the region of ancient Sparta. When threatened that if we invade, we will destroy you, the Spartans replied: If."),
        entry("halcyon", "adjective",
              "Calm, happy and peaceful, usually describing the past.",
              "We remember those halcyon summer holidays at grandma's house.",
              "From Greek halkyon, kingfisher. The bird was believed to calm the sea while it nested."),
        entry("onomatopoeia", "noun",
              "A word that sounds like the thing it describes, such as buzz or sizzle.",
              "Comic books are full of onomatopoeia: bang, pow, whoosh.",
              "From Greek onoma, name, and poiein, to make: name-making."),
        entry("palindrome", "noun",
              "A word or phrase that reads the same backwards, such as racecar.",
              "Madam, in Eden, I'm Adam is a famous palindrome.",
              "From Greek palindromos, running back again."),
        entry("hyperbole", "noun",
              "Deliberate exaggeration.",
              "I have told you a million times is a classic piece of hyperbole.",
              "From Greek hyper, beyond, and ballein, to throw: throwing beyond."),
        entry("oxymoron", "noun",
              "Two opposite words used together, like deafening silence.",
              "Jumbo shrimp is everyone's favourite oxymoron.",
              "From Greek oxys, sharp, and moros, dull. The word itself is an oxymoron: sharp-dull."),
        entry("epiphany", "noun",
              "A sudden moment of understanding.",
              "In the shower, I had an epiphany about the maths homework.",
              "From Greek epiphaneia, appearance or showing forth."),
        entry("melancholy", "noun",
              "A deep, thoughtful sadness.",
              "Rainy Sunday evenings bring a gentle melancholy.",
              "From Greek melas, black, and khole, bile. Ancient doctors blamed sadness on too much black bile."),
        entry("sanguine", "adjective",
              "Cheerfully optimistic.",
              "Despite the rain, she was sanguine about the picnic.",
              "From Latin sanguis, blood. Medieval doctors believed people with plenty of blood were cheerful."),
        entry("phlegmatic", "adjective",
              "Calm and hard to excite.",
              "Our phlegmatic cat did not even blink at the fireworks.",
              "From phlegm, one of the four body fluids that ancient medicine said controlled your temper."),
        entry("tranquil", "adjective",
              "Peaceful and calm.",
              "The lake was so tranquil that it reflected every cloud.",
              "From Latin tranquillus, quiet or still."),
        entry("serene", "adjective",
              "Calm and untroubled.",
              "She looked serene even as the toddlers ran riot around her.",
              "From Latin serenus, clear and cloudless, as in a calm sky."),
        entry("luminous", "adjective",
              "Giving off light; glowing.",
              "The luminous stars on my ceiling glow for an hour after lights out.",
              "From Latin lumen, light."),
        entry("effervescent", "adjective",
              "Bubbly; full of lively energy.",
              "Her effervescent laugh made everyone else laugh too.",
              "From Latin effervescere, to boil up."),
        entry("iridescent", "adjective",
              "Showing shimmering colours that change with the angle of view.",
              "The soap bubble was iridescent pink, green and gold.",
              "From Greek iris, rainbow, also the name of the goddess of the rainbow."),
        entry("gossamer", "noun",
              "Fine cobwebs floating in the air; anything very light and delicate.",
              "The morning grass was covered in silver gossamer.",
              "From Middle English gos somer, goose summer, a mild spell in late autumn when geese were eaten and cobwebs drifted in the air."),
        entry("lollygag", "verb",
              "To waste time; to dawdle.",
              "Stop lollygagging, the bus leaves in two minutes!",
              "American slang from the 1800s; nobody knows exactly where it came from."),
        entry("skedaddle", "verb",
              "To run away quickly.",
              "When the dog saw the bath, it skedaddled under the bed.",
              "American slang that became popular during the Civil War in the 1860s; its origin is a mystery."),
        entry("hornswoggle", "verb",
              "To trick or cheat someone.",
              "The street magician hornswoggled us out of our last coins.",
              "A made-up word from the American frontier of the early 1800s."),
        entry("shenanigans", "noun",
              "Silly or mischievous behaviour.",
              "No shenanigans while I am on the phone, said Mum.",
              "First recorded in California in the 1850s; its origin is uncertain, possibly from an Irish phrase about playing the fox."),
        entry("rigmarole", "noun",
              "A long, complicated process.",
              "Renewing a passport is quite a rigmarole.",
              "From ragman roll, a long medieval scroll or list of names."),
        entry("hodgepodge", "noun",
              "A confused mixture.",
              "The lunchbox was a hodgepodge of leftovers.",
              "From hotchpotch, from French hochepot, a stew shaken together in a pot."),
        entry("higgledy-piggledy", "adjective",
              "In confusion or disorder.",
              "Shoes were piled higgledy-piggledy by the front door.",
              "A rhyming phrase from the 1500s, probably inspired by how pigs huddle together."),
        entry("willy-nilly", "adverb",
              "Whether you like it or not; or without a plan.",
              "Toys were thrown willy-nilly into the box.",
              "From will I, nill I: whether I want it or not. Nill meant to be unwilling."),
        entry("namby-pamby", "adjective",
              "Weak, soppy and sentimental.",
              "The villain in the film was surprisingly namby-pamby.",
              "A mocking nickname given in the 1720s to the poet Ambrose Philips, whose verses for children were thought too sugary."),
        entry("flibbertigibbet", "noun",
              "A silly, chattering, flighty person.",
              "The parrot is a flibbertigibbet, squawking about everything.",
              "An old imitation of rapid chatter. Shakespeare used it as the name of a mischievous devil in King Lear."),
        entry("whippersnapper", "noun",
              "A young person who is cheeky or overconfident.",
              "That whippersnapper beat me at chess in six moves!",
              "From the 1600s, perhaps from whip-snapper, an idle youth who just snapped whips."),
        entry("curmudgeon", "noun",
              "A bad-tempered, grumpy person, often an old one.",
              "The curmudgeon next door secretly feeds all the street cats.",
              "Recorded since the 1500s; where it came from is a complete mystery."),
        entry("scallywag", "noun",
              "A mischievous person, especially a child.",
              "Some scallywag ate all the chocolate biscuits.",
              "American slang from the 1840s, of unknown origin."),
        entry("poppycock", "noun",
              "Nonsense.",
              "Grandpa says the idea that carrots help you see in the dark is poppycock, mostly.",
              "From Dutch dialect pappekak, soft dung."),
        entry("balderdash", "noun",
              "Senseless talk or writing.",
              "His story about meeting a talking crow was pure balderdash.",
              "From the 1590s, when it meant a frothy liquid or a jumble of drinks; later, a jumble of words."),
        entry("gibberish", "noun",
              "Meaningless or unintelligible talk.",
              "The baby babbled happy gibberish at the ceiling fan.",
              "From the 1550s, probably from gibber, to chatter, which imitates the sound."),
        entry("widdershins", "adverb",
              "Anticlockwise; in the opposite direction to the sun.",
              "We walked widdershins round the pond just to be different.",
              "From Middle Low German weddersinnes, against the way. Walking widdershins was once considered unlucky."),
        entry("bumbershoot", "noun",
              "A playful word for an umbrella.",
              "Do not forget your bumbershoot, it is pouring!",
              "American slang from the 1890s, a jokey mix of umbrella and parachute."),
        entry("collywobbles", "noun",
              "A nervous, fluttery feeling in the stomach.",
              "I always get the collywobbles before going on stage.",
              "From the 1820s, probably from colic, a stomach ache, and wobble."),
        entry("smithereens", "noun",
              "Small broken pieces.",
              "The vase fell and shattered into smithereens.",
              "From Irish smidirin, a small fragment."),
        entry("bodacious", "adjective",
              "Excellent, impressive or bold.",
              "That was a bodacious skateboard jump.",
              "American, probably a blend of bold and audacious."),
        entry("ragamuffin", "noun",
              "A person, especially a child, in ragged, dirty clothes.",
              "After the mud fight, the kids came home looking like ragamuffins.",
              "From Ragamoffyn, the name of a demon in the 14th-century poem Piers Plowman."),
        entry("humdinger", "noun",
              "A remarkable or outstanding person or thing.",
              "The final over was a real humdinger.",
              "American slang from around 1900, of uncertain origin."),
        entry("cahoots", "noun",
              "Secret partnership, as in in cahoots.",
              "The twins are in cahoots to hide the remote.",
              "American slang from the 1820s, possibly from French cahute, a cabin or hut."),
        entry("hunky-dory", "adjective",
              "Fine; going well.",
              "After the rain stopped, everything was hunky-dory.",
              "American slang from the 1860s, perhaps from Dutch honk, home or goal in children's games."),
        entry("okay", "adjective",
              "All right; acceptable.",
              "Is it okay if I take the last slice?",
              "Born in 1839 as a joke in a Boston newspaper: O.K. for oll korrect, a deliberate misspelling of all correct. A US president's 1840 campaign made it famous."),
        entry("malarkey", "noun",
              "Nonsense or foolish talk.",
              "Do not believe his malarkey about owning a pet tiger.",
              "American slang from the 1920s; its origin is unknown."),
        entry("bonanza", "noun",
              "A sudden source of great wealth or luck.",
              "The sale was a bonanza for book lovers.",
              "Spanish for fair weather or prosperity. American miners used it for a rich seam of ore."),
        entry("benevolent", "adjective",
              "Kind and well-meaning.",
              "A benevolent stranger paid for our tea.",
              "From Latin bene, well, and volens, wishing."),
        entry("magnanimous", "adjective",
              "Generous and forgiving, especially towards a rival.",
              "She was magnanimous in victory and shook every hand.",
              "From Latin magnus, great, and animus, soul: great-souled."),
        entry("gregarious", "adjective",
              "Fond of company; sociable.",
              "Our gregarious neighbour knows everyone in the building.",
              "From Latin grex, flock. Gregarious animals live in flocks or herds."),
        entry("candid", "adjective",
              "Honest and direct.",
              "Thanks for your candid opinion of my haircut.",
              "From Latin candidus, white or pure, the same root as candidate."),
        entry("meticulous", "adjective",
              "Showing great attention to detail.",
              "He is meticulous about lining up his pencils by length.",
              "From Latin meticulosus, fearful, from metus, fear. Being afraid of mistakes made people careful."),
        entry("fastidious", "adjective",
              "Very concerned about details, cleanliness or correctness.",
              "The fastidious cat refused to eat from a slightly dusty bowl.",
              "From Latin fastidium, loathing or disgust."),
        entry("pensive", "adjective",
              "Deep in thought.",
              "She looked pensive, staring out of the train window.",
              "From French penser, to think."),
        entry("jubilant", "adjective",
              "Feeling or showing great happiness.",
              "The jubilant fans danced in the street.",
              "From Latin jubilare, to shout for joy."),
        entry("tenacious", "adjective",
              "Holding on firmly; not giving up.",
              "The tenacious ant carried a crumb twice its size.",
              "From Latin tenere, to hold."),
        entry("audacious", "adjective",
              "Bold and daring.",
              "It was an audacious plan to build a treehouse in one day.",
              "From Latin audax, bold."),
        entry("vivacious", "adjective",
              "Lively and full of spirit.",
              "The vivacious tour guide made a museum of spoons fun.",
              "From Latin vivax, lively, from vivere, to live."),
        entry("pragmatic", "adjective",
              "Dealing with things sensibly and practically.",
              "Being pragmatic, we packed raincoats and sunglasses.",
              "From Greek pragma, deed or thing done."),
        entry("enigma", "noun",
              "A person or thing that is mysterious and hard to understand.",
              "Why my cat sits in boxes is an enigma.",
              "From Greek ainigma, riddle."),
        entry("labyrinth", "noun",
              "A complicated maze.",
              "The old city's streets were a labyrinth of tiny alleys.",
              "From Greek labyrinthos, the maze built for the Minotaur in the legend of King Minos of Crete."),
        entry("paraphernalia", "noun",
              "The many small items needed for an activity.",
              "Babies come with a lot of paraphernalia.",
              "From Greek parapherna, a bride's own belongings beyond her dowry."),
        entry("cornucopia", "noun",
              "An abundant supply of good things.",
              "The wedding buffet was a cornucopia of sweets.",
              "From Latin cornu copiae, horn of plenty, a mythical goat's horn overflowing with fruit and grain."),
        entry("perspicacious", "adjective",
              "Quick to notice and understand things.",
              "The perspicacious detective spotted the clue in seconds.",
              "From Latin perspicere, to look through or see clearly."),
        entry("obfuscate", "verb",
              "To make something unclear or confusing.",
              "The long instructions only obfuscated a simple task.",
              "From Latin ob, over, and fuscus, dark: to darken."),
        entry("ruminate", "verb",
              "To think deeply about something for a long time.",
              "I ruminated over the menu for ten minutes and then ordered the usual.",
              "From Latin ruminare, to chew the cud, as cows do, chewing food over and over."),
        entry("procrastinate", "verb",
              "To keep putting off something that needs doing.",
              "I procrastinated by cleaning my whole room instead of doing homework.",
              "From Latin pro, forward, and crastinus, belonging to tomorrow."),
        entry("ambivalent", "adjective",
              "Having mixed feelings.",
              "I am ambivalent about pineapple on pizza.",
              "From German Ambivalenz, coined by Swiss psychiatrist Eugen Bleuler around 1910, from Latin ambi, both, and valere, to be strong."),
        entry("ineffable", "adjective",
              "Too great or beautiful to be described in words.",
              "The view from the summit filled us with ineffable joy.",
              "From Latin in, not, and effabilis, able to be spoken."),
        entry("quintessential", "adjective",
              "The most perfect example of something.",
              "Hot chai on a rainy day is the quintessential comfort.",
              "From Latin quinta essentia, the fifth essence. Ancient thinkers believed the heavens were made of a fifth element beyond earth, water, air and fire."),
        entry("clandestine", "adjective",
              "Kept secret.",
              "We held a clandestine meeting to plan Dad's surprise party.",
              "From Latin clam, secretly."),
        entry("surreptitious", "adjective",
              "Done secretly so others do not notice.",
              "He took a surreptitious bite of the cake before it was cut.",
              "From Latin surripere, to snatch secretly."),
        entry("nefarious", "adjective",
              "Wicked or criminal.",
              "The cat had a nefarious plan involving the fish tank.",
              "From Latin nefas, a wrong or crime."),
        entry("impeccable", "adjective",
              "Without any faults.",
              "Her handwriting is impeccable.",
              "From Latin in, not, and peccare, to sin or make a mistake."),
        entry("immaculate", "adjective",
              "Perfectly clean and tidy.",
              "The kitchen was immaculate before the guests arrived, and only then.",
              "From Latin in, not, and macula, spot or stain."),
        entry("ostentatious", "adjective",
              "Showy, designed to impress.",
              "He wore an ostentatious gold watch to the picnic.",
              "From Latin ostendere, to show."),
        entry("capricious", "adjective",
              "Changing mood or behaviour suddenly.",
              "The capricious weather ruined three picnics in a row.",
              "From Italian capriccio, a sudden fancy, perhaps from capo, head, and riccio, hedgehog: hair standing on end."),
        entry("whimsical", "adjective",
              "Playfully unusual or fanciful.",
              "The cafe had whimsical teapots shaped like animals.",
              "From whim, short for whim-wham, an old word for a trinket or fanciful notion."),
        entry("garrulous", "adjective",
              "Talking too much about unimportant things.",
              "The garrulous parrot kept repeating the doorbell sound.",
              "From Latin garrire, to chatter."),
        entry("taciturn", "adjective",
              "Saying very little; reserved.",
              "The taciturn farmer answered every question with a nod.",
              "From Latin tacitus, silent, from tacere, to be silent."),
        entry("succinct", "adjective",
              "Brief and clearly expressed.",
              "Her speech was succinct: thank you, and let's eat.",
              "From Latin succinctus, tucked up or girded, like a robe tied up tight for action."),
        entry("ludicrous", "adjective",
              "So silly it is laughable.",
              "The idea of a cat walking on a lead seemed ludicrous until we saw one.",
              "From Latin ludus, play or game."),
        entry("facetious", "adjective",
              "Treating serious things with silly humour.",
              "His facetious reply did not help us find the keys.",
              "From Latin facetia, a jest."),
        entry("jocular", "adjective",
              "Fond of joking; humorous.",
              "The jocular pilot made the whole plane laugh before take-off.",
              "From Latin jocus, joke."),
        entry("cordial", "adjective",
              "Warm and friendly.",
              "The neighbours gave us a cordial welcome with sweets.",
              "From Latin cor, heart."),
        entry("courage", "noun",
              "The ability to do something that frightens you.",
              "It took courage to sing alone at the assembly.",
              "From Old French corage, from Latin cor, heart. The heart was seen as the seat of feelings."),
        entry("nonchalant", "adjective",
              "Calm and casual, seeming not to care.",
              "He was nonchalant about winning, but practised every night.",
              "From French non, not, and chaloir, to be concerned."),
        entry("debonair", "adjective",
              "Stylish, charming and confident.",
              "The debonair waiter carried six plates without a wobble.",
              "From Old French de bon aire, of good nature. It was first used of hawks with a good temperament."),
        entry("savvy", "adjective",
              "Shrewd and knowledgeable.",
              "My savvy grandmother found the best deal in the whole market.",
              "From pidgin English, based on Spanish or Portuguese sabe, he knows."),
        entry("panache", "noun",
              "Flamboyant confidence and style.",
              "He served the omelette with great panache.",
              "French for a plume of feathers on a helmet, a sign of a dashing knight."),
        entry("aplomb", "noun",
              "Calm self-confidence under pressure.",
              "She handled the broken microphone with aplomb.",
              "From French a plomb, upright, by the plumb line, a weight used to check if walls stand straight."),
        entry("gusto", "noun",
              "Great enjoyment and energy.",
              "The kids sang the song with tremendous gusto.",
              "Italian for taste, from Latin gustus."),
        entry("flair", "noun",
              "A natural talent or stylish way of doing something.",
              "He has a flair for making up silly songs.",
              "From Old French flairier, to smell: having a good nose for something."),
        entry("moxie", "noun",
              "Courage, energy and determination.",
              "It took real moxie to challenge the champion.",
              "From Moxie, an American soft drink of the 1880s advertised as a nerve tonic."),
        entry("chutzpah", "noun",
              "Shameless boldness.",
              "He had the chutzpah to ask the chef for the recipe and a second helping.",
              "From Yiddish khutspe, from Hebrew, meaning insolence or audacity."),
        entry("glitch", "noun",
              "A sudden small fault or problem.",
              "A glitch in the game made my character walk through walls.",
              "Probably from Yiddish glitsh, a slip. It spread through American space programme slang in the 1960s."),
        entry("klutz", "noun",
              "A clumsy person.",
              "I am such a klutz, I tripped over a painted line.",
              "From Yiddish klots, a wooden block."),
        entry("schmooze", "verb",
              "To chat in a friendly way, often to gain something.",
              "He schmoozed the shopkeeper into giving us a discount.",
              "From Yiddish shmuesn, to chat."),
        entry("smorgasbord", "noun",
              "A buffet of many dishes; a wide variety.",
              "The festival was a smorgasbord of music, food and games.",
              "From Swedish smorgas, open sandwich, and bord, table."),
        entry("ombudsman", "noun",
              "An official who investigates complaints against organisations.",
              "She wrote to the ombudsman about the late trains.",
              "Swedish for representative or agent."),
    ]
}
