import Foundation

// MARK: - Word of the Day list, part three

extension WordDayList {
    static let partThree: [WordDayEntry] = [
        entry("berserk", "adjective",
              "Out of control with anger or excitement.",
              "The dog went berserk when it saw the postman.",
              "From Old Norse berserkr, probably bear-shirt: Norse warriors said to fight in a wild frenzy."),
        entry("ransack", "verb",
              "To search a place roughly, making a mess.",
              "I ransacked the cupboard looking for the birthday candles.",
              "From Old Norse rannsaka, to search a house: rann, house, and saka, to seek."),
        entry("slogan", "noun",
              "A short, memorable phrase used in advertising or campaigns.",
              "Our class slogan was: no homework on Fridays.",
              "From Scottish Gaelic sluagh-ghairm, a battle cry: sluagh, army, and gairm, shout."),
        entry("galore", "adjective",
              "In large amounts.",
              "There were sweets galore at the wedding.",
              "From Irish go leor, enough or plenty. It is one of the few English adjectives that comes after its noun."),
        entry("kindergarten", "noun",
              "A school or class for very young children.",
              "My little sister loves her kindergarten because it has a sandpit.",
              "German for children's garden, coined in 1840 by educator Friedrich Froebel, who believed children should grow like plants."),
        entry("hamster", "noun",
              "A small furry rodent with cheek pouches, often kept as a pet.",
              "Our hamster stores sunflower seeds in its cheeks like a tiny suitcase.",
              "From German. In German, hamstern means to hoard, just as hamsters stuff their cheeks with food."),
        entry("poodle", "noun",
              "A dog breed with a curly coat.",
              "The poodle at the park had a haircut fancier than mine.",
              "From German Pudel, short for Pudelhund, splash dog. Poodles were bred to fetch ducks from water."),
        entry("pretzel", "noun",
              "A knot-shaped baked snack.",
              "He twisted himself into a pretzel trying to reach the remote.",
              "From German Brezel, from Latin bracchium, arm. The shape is said to look like arms folded in prayer."),
        entry("cliche", "noun",
              "A phrase or idea used so often that it has lost its impact.",
              "Saying it was a dark and stormy night is a famous cliche.",
              "A French printers' word for a metal printing plate used to print the same thing again and again, probably imitating the click of the mould."),
        entry("rendezvous", "noun",
              "An arranged meeting at a set time and place.",
              "Our rendezvous point was the big clock at the station.",
              "From French rendez-vous, present yourselves."),
        entry("entrepreneur", "noun",
              "Someone who starts a business and takes risks to make it work.",
              "At ten, she was already an entrepreneur selling homemade bookmarks.",
              "French for one who undertakes, from entreprendre, to undertake."),
        entry("etiquette", "noun",
              "The rules of polite behaviour.",
              "Phone etiquette says no loud calls in the library.",
              "French for a ticket or label. Rules of behaviour at the royal court were said to be written on small cards."),
        entry("denim", "noun",
              "A strong cotton fabric used for jeans.",
              "His denim jacket is older than he is: it was his father's.",
              "From French serge de Nimes, fabric from the city of Nimes in southern France."),
        entry("trampoline", "noun",
              "A stretchy sheet on a frame for bouncing.",
              "We bounced on the trampoline until our legs felt like noodles.",
              "From Italian trampolino, springboard. The modern trampoline was built by American gymnast George Nissen in the 1930s."),
        entry("frisbee", "noun",
              "A flying disc thrown for fun.",
              "The dog caught the frisbee in mid-air and ran off with it.",
              "From the Frisbie Pie Company of Connecticut. Students tossed its empty pie tins to each other for fun."),
        entry("teddy", "noun",
              "A soft toy bear.",
              "Even at fifteen, he still has his old teddy on the shelf.",
              "Named after US President Theodore Teddy Roosevelt, who refused to shoot a captured bear on a hunting trip in 1902. A toy maker named a bear after him."),
        entry("yo-yo", "noun",
              "A toy that spins down and climbs back up a string.",
              "My yo-yo only goes down, never back up.",
              "The name was popularised by Pedro Flores, a Filipino American who started making yo-yos in California in 1928; it probably comes from the Ilocano language."),
        entry("tabby", "noun",
              "A cat with a striped coat.",
              "The tabby slept in a stripe of sunshine, matching it perfectly.",
              "From Attabiy, a district of Baghdad famous for its striped silk."),
        entry("calico", "noun",
              "A plain cotton cloth.",
              "She sewed a calico bag for her library books.",
              "From Calicut, now Kozhikode, in Kerala, from where the cloth was shipped to Europe."),
        entry("khaki", "noun",
              "A dull yellowish-brown colour or fabric.",
              "The explorers wore khaki shirts and enormous hats.",
              "From Urdu and Persian khak, dust. British soldiers in India dyed their uniforms dust-coloured in the 1840s."),
        entry("cashmere", "noun",
              "Very soft wool from a particular kind of goat.",
              "Her cashmere scarf was as soft as a kitten.",
              "From Kashmir, home of the goats whose fine wool was woven into famous shawls."),
        entry("amok", "adverb",
              "Behaving in a wild, uncontrolled way, as in run amok.",
              "The goats ran amok in the vegetable garden.",
              "From Malay amuk, rushing in a frenzy."),
        entry("orangutan", "noun",
              "A large, red-haired ape from Borneo and Sumatra.",
              "The orangutan used a leaf as an umbrella.",
              "From Malay orang, person, and hutan, forest: person of the forest."),
        entry("tattoo", "noun",
              "A design made permanently on the skin.",
              "My uncle has a tattoo of his first motorbike.",
              "From Polynesian tatau, recorded by Captain Cook's crew in Tahiti in 1769."),
        entry("taboo", "noun",
              "Something that is not allowed or not talked about.",
              "In our house, spoilers are a strict taboo.",
              "From Tongan tapu, forbidden or sacred, recorded by Captain Cook in 1777."),
        entry("ukulele", "noun",
              "A small four-stringed guitar from Hawaii.",
              "He learned three chords on the ukulele and wrote ten songs.",
              "Hawaiian, often translated as jumping flea, perhaps after the quick finger movements. It grew from a small guitar brought by Portuguese immigrants in 1879."),
        entry("igloo", "noun",
              "A dome-shaped house built from blocks of snow.",
              "We built a tiny igloo for my toy penguin.",
              "From Inuktitut iglu, which simply means house."),
        entry("raccoon", "noun",
              "A North American animal with a black mask and ringed tail.",
              "The raccoon opened the bin lid like a professional.",
              "From Powhatan, recorded in the early 1600s by John Smith of Jamestown as aroughcun."),
        entry("aurora", "noun",
              "Natural coloured lights in the sky near the poles.",
              "We stayed up all night hoping to see the aurora dance.",
              "Latin for dawn, after the Roman goddess of dawn. Galileo is often credited with naming the aurora borealis, the northern dawn."),
        entry("comet", "noun",
              "An icy body in space that grows a glowing tail near the sun.",
              "The comet looked like a smudge with a long, faint tail.",
              "From Greek kometes, long-haired, because the tail looked like flowing hair."),
        entry("planet", "noun",
              "A large body that orbits a star.",
              "Jupiter is so big that all the other planets could fit inside it.",
              "From Greek planetes, wanderer, because planets moved across the sky while stars stayed put."),
        entry("galaxy", "noun",
              "A huge system of stars, gas and dust.",
              "Our galaxy holds more than a hundred billion stars.",
              "From Greek galaxias, milky, from gala, milk, as in the Milky Way."),
        entry("asteroid", "noun",
              "A small rocky body orbiting the sun.",
              "Most asteroids orbit between Mars and Jupiter.",
              "Coined in 1802 by astronomer William Herschel from Greek asteroeides, star-like."),
        entry("solstice", "noun",
              "The longest or shortest day of the year.",
              "We watched the sunrise on the summer solstice.",
              "From Latin sol, sun, and sistere, to stand still: the sun seems to pause before turning back."),
        entry("quark", "noun",
              "A tiny particle that makes up protons and neutrons.",
              "Everything around you is made partly of quarks.",
              "Physicist Murray Gell-Mann took the name from a line in James Joyce's Finnegans Wake: Three quarks for Muster Mark!"),
        entry("googol", "noun",
              "The number 1 followed by 100 zeros.",
              "There are not a googol grains of sand on every beach on Earth put together.",
              "Named by nine-year-old Milton Sirotta, nephew of mathematician Edward Kasner. The search engine Google was named after a misspelling of it."),
        entry("tulip", "noun",
              "A bright cup-shaped spring flower.",
              "The tulips opened in the morning and closed again at night.",
              "From Turkish tulbent, turban, because the flower looks like one."),
        entry("daisy", "noun",
              "A small flower with white petals and a yellow centre.",
              "We made a daisy chain long enough to go round the dog.",
              "From Old English daeges eage, day's eye, because it opens in the morning and closes at night."),
        entry("dandelion", "noun",
              "A yellow wild flower that turns into a fluffy seed head.",
              "Blowing a dandelion clock is the best way to tell the time badly.",
              "From French dent de lion, lion's tooth, after its jagged leaves."),
        entry("lemur", "noun",
              "A tree-climbing primate from Madagascar with big eyes.",
              "The ring-tailed lemurs sunbathed with their arms out.",
              "From Latin lemures, ghosts of the dead. Scientist Carl Linnaeus chose it for the animals' night habits and ghostly stare."),
        entry("aardvark", "noun",
              "An African animal that eats ants and termites.",
              "Aardvark is often the first animal in the dictionary.",
              "From Afrikaans aarde, earth, and vark, pig."),
        entry("chameleon", "noun",
              "A lizard that can change colour.",
              "The chameleon's eyes looked in two directions at once.",
              "From Greek khamai, on the ground, and leon, lion: ground lion."),
        entry("ladybird", "noun",
              "A small red beetle with black spots.",
              "A ladybird landed on my book and walked across the page.",
              "Named for Our Lady, the Virgin Mary, who was often painted in a red cloak."),
        entry("pterodactyl", "noun",
              "A flying reptile from the time of the dinosaurs.",
              "My brother runs around the garden flapping like a pterodactyl.",
              "From Greek pteron, wing, and daktylos, finger: its wing was stretched on one very long finger."),
        entry("axolotl", "noun",
              "A Mexican salamander that keeps its frilly gills for life.",
              "The axolotl seemed to smile at everyone who passed the tank.",
              "From Nahuatl atl, water, and Xolotl, the name of an Aztec god; often translated as water monster."),
        entry("murmuration", "noun",
              "A huge flock of starlings swooping and swirling together.",
              "At sunset, a murmuration painted shapes across the sky.",
              "From murmur, after the soft rushing sound of thousands of wings."),
        entry("crepuscular", "adjective",
              "Active at twilight, at dawn or dusk.",
              "Rabbits are crepuscular, which is why we see them at dusk.",
              "From Latin crepusculum, twilight."),
        entry("bioluminescence", "noun",
              "Light made by living things.",
              "Every wave glowed blue with bioluminescence.",
              "From Greek bios, life, and Latin lumen, light."),
        entry("hiraeth", "noun",
              "A deep longing for home, or for a place you can never return to.",
              "Hearing the old song filled her with hiraeth for her grandparents' village.",
              "A Welsh word with no exact English equivalent."),
        entry("saudade", "noun",
              "A bittersweet longing for something or someone loved and missed.",
              "Old holiday photos fill me with saudade.",
              "Portuguese; it is central to fado, Portugal's mournful folk music."),
        entry("ikigai", "noun",
              "Your reason for getting up in the morning; what makes life worthwhile.",
              "Teaching children to swim is my grandfather's ikigai.",
              "Japanese, from iki, life, and gai, worth or value."),
        entry("tsundoku", "noun",
              "Buying books and letting them pile up unread.",
              "My bedside table is a monument to tsundoku.",
              "Japanese slang from the 1800s: tsunde oku, to pile up and leave, and doku, reading."),
        entry("kintsugi", "noun",
              "The art of mending broken pottery with gold.",
              "The cracked bowl, repaired by kintsugi, became more beautiful than before.",
              "Japanese, from kin, gold, and tsugi, joining."),
        entry("komorebi", "noun",
              "Sunlight filtering through the leaves of trees.",
              "We lay on the grass watching the komorebi flicker.",
              "Japanese, from words for tree, leaking through, and sunlight."),
        entry("lagom", "noun",
              "Just the right amount; not too much, not too little.",
              "Lagom is how much chilli Grandma puts in the curry, she claims.",
              "Swedish. A popular tale says Vikings passed round a drinking horn so everyone got a fair share, but this is probably a myth."),
        entry("hygge", "noun",
              "A cosy, warm feeling of comfort and contentment.",
              "Blankets, candles and hot chocolate: pure hygge.",
              "Danish, from an old Norwegian word meaning wellbeing."),
        entry("jugaad", "noun",
              "A clever, improvised fix using whatever is at hand.",
              "Using a clothes peg to fix the fan was classic jugaad.",
              "From Hindi, used across India for creative, low-cost problem solving."),
        entry("ubuntu", "noun",
              "The belief that we are all connected by our shared humanity.",
              "The village's ubuntu meant nobody ate alone.",
              "From Nguni Bantu languages such as Zulu and Xhosa, often explained as I am because we are."),
        entry("sobremesa", "noun",
              "Time spent chatting at the table after a meal.",
              "The sobremesa lasted longer than the lunch.",
              "Spanish, from sobre, over, and mesa, table."),
        entry("gumption", "noun",
              "Common sense and the courage to act on it.",
              "It took gumption to ask the shopkeeper for a refund.",
              "Scottish, from the early 1700s; its origin is unknown."),
        entry("empathy", "noun",
              "The ability to understand and share another person's feelings.",
              "Her empathy made her the friend everyone called first.",
              "Coined in English in 1909 by psychologist Edward Titchener to translate German Einfuhlung, feeling into, using Greek empatheia."),
        entry("altruism", "noun",
              "Caring about others more than yourself.",
              "Giving up his window seat was pure altruism.",
              "Coined in French by philosopher Auguste Comte in the 1830s from Latin alter, other."),
        entry("catharsis", "noun",
              "The release of strong emotions, leaving you feeling better.",
              "Having a good cry at the film was a real catharsis.",
              "From Greek katharsis, cleansing. Aristotle used it for the release of feelings an audience gets from tragedy."),
        entry("equanimity", "noun",
              "Calmness, especially in a difficult situation.",
              "She accepted the cancelled trip with equanimity.",
              "From Latin aequus, even, and animus, mind."),
        entry("solace", "noun",
              "Comfort in a time of sadness.",
              "He found solace in long walks with his dog.",
              "From Latin solacium, comfort."),
        entry("reverie", "noun",
              "A pleasant daydream.",
              "The school bell snapped me out of my reverie.",
              "From French rever, to dream."),
        entry("elated", "adjective",
              "Extremely happy and excited.",
              "She was elated to find her lost earring in the sofa.",
              "From Latin elatus, raised up or lifted."),
        entry("zany", "adjective",
              "Amusingly unusual and silly.",
              "The clown's zany tricks had the toddlers shrieking.",
              "From Italian zanni, a comic servant in old Italian street theatre, a nickname for Giovanni."),
        entry("buffoon", "noun",
              "A person who behaves ridiculously but is amusing.",
              "He played the buffoon to cheer up his little sister.",
              "From Italian buffone, jester, from buffa, joke."),
        entry("slapstick", "noun",
              "Comedy based on clumsy actions and silly accidents.",
              "Slipping on a banana peel is classic slapstick.",
              "From a stick made of two flat pieces of wood that made a loud slap when a clown was hit, without hurting."),
        entry("abracadabra", "exclamation",
              "A word said by magicians when performing a trick.",
              "Abracadabra! And the coin vanished from his hand.",
              "Recorded by the Roman physician Serenus Sammonicus around 200 AD, who wrote it in a triangle as a charm against fever."),
        entry("gadget", "noun",
              "A small, clever device.",
              "Dad's new kitchen gadget peels, slices and confuses everyone.",
              "Sailors' slang from the 1800s for any small tool whose name you could not remember."),
        entry("portmanteau", "noun",
              "A word made by blending two others, such as brunch.",
              "Smog is a portmanteau of smoke and fog.",
              "From French porter, to carry, and manteau, cloak: a suitcase that opens into two halves. Lewis Carroll used it for blended words."),
        entry("spoonerism", "noun",
              "Swapping the first sounds of two words by mistake.",
              "Saying a blushing crow instead of a crushing blow is a spoonerism.",
              "Named after Reverend William Spooner of Oxford University, who was famous for slips like these."),
        entry("pangram", "noun",
              "A sentence that uses every letter of the alphabet.",
              "The quick brown fox jumps over the lazy dog is the best-known pangram.",
              "From Greek pan, all, and gramma, letter."),
        entry("mondegreen", "noun",
              "A misheard song lyric or phrase.",
              "For years I sang a mondegreen about a bathroom on the right.",
              "Coined in 1954 by writer Sylvia Wright, who misheard laid him on the green in a ballad as Lady Mondegreen."),
        entry("triskaidekaphobia", "noun",
              "Fear of the number thirteen.",
              "The hotel has no thirteenth floor, thanks to triskaidekaphobia.",
              "From Greek treiskaideka, thirteen, and phobia, fear."),
        entry("susurrus", "noun",
              "A soft whispering or rustling sound.",
              "The susurrus of the leaves sent me to sleep.",
              "Latin for whisper, a word that sounds like what it means."),
        entry("crescendo", "noun",
              "A gradual increase in loudness; a climax.",
              "The fireworks reached a crescendo of colour at midnight.",
              "Italian for growing."),
        entry("encore", "noun",
              "An extra performance demanded by an audience.",
              "The crowd shouted for an encore until the band came back.",
              "French for again, though French audiences actually shout bis instead."),
        entry("virtuoso", "noun",
              "A person with outstanding skill, especially in music.",
              "The young violinist played like a virtuoso.",
              "Italian for skilled or learned."),
        entry("serenade", "noun",
              "A song performed for someone, often outdoors in the evening.",
              "The frogs gave us a loud serenade all night.",
              "From Italian serenata, evening music in the open air, from sereno, the clear evening sky."),
        entry("lullaby", "noun",
              "A soft song sung to send a child to sleep.",
              "Grandma's lullaby works on babies, dogs and adults.",
              "From lulla and by-by, soothing sounds people have sung to babies for centuries."),
        entry("orchestra", "noun",
              "A large group of musicians playing together.",
              "The orchestra tuned up with a noise like a hundred bees.",
              "In ancient Greek theatre, the orkhestra was the space in front of the stage where the chorus danced."),
        entry("protagonist", "noun",
              "The main character in a story.",
              "The protagonist of my favourite book is a talking bicycle.",
              "From Greek protos, first, and agonistes, actor or competitor."),
        entry("museum", "noun",
              "A building where interesting objects are kept and displayed.",
              "We spent a whole day at the museum and still missed the dinosaurs.",
              "From Greek mouseion, a place of the Muses, the goddesses of the arts and learning."),
        entry("library", "noun",
              "A place where books are kept for people to read or borrow.",
              "The library is the quietest place in town, except for the sneezing.",
              "From Latin liber, book, which first meant the inner bark of trees, an early writing material."),
        entry("calendar", "noun",
              "A chart showing the days, weeks and months of a year.",
              "Every birthday is circled in red on our kitchen calendar.",
              "From Latin kalendae, the first day of each Roman month, when debts had to be paid."),
        entry("biscuit", "noun",
              "A small, crisp baked treat.",
              "The best biscuits are the ones dunked in tea for exactly three seconds.",
              "From Latin bis coctus, twice cooked, through French. Ships' biscuits were baked twice to last long voyages."),
        entry("cappuccino", "noun",
              "Coffee topped with frothy milk.",
              "Mum's cappuccino moustache made us all laugh.",
              "Named after the Capuchin friars, whose brown hooded robes matched the coffee's colour."),
        entry("marmalade", "noun",
              "A jam made from citrus fruit, usually oranges.",
              "Paddington Bear always keeps a marmalade sandwich under his hat.",
              "From Portuguese marmelada, quince jam, from marmelo, quince."),
        entry("chutney", "noun",
              "A spicy relish made of fruit or vegetables.",
              "Mint chutney makes every samosa better.",
              "From Hindi chatni, from chatna, to lick."),
        entry("mulligatawny", "noun",
              "A spicy soup.",
              "The cafe's mulligatawny warmed us up after the rain.",
              "From Tamil milagu tannir, pepper water."),
        entry("ginger", "noun",
              "A hot, spicy root used in cooking.",
              "Ginger tea is my grandmother's cure for everything.",
              "From Sanskrit shringavera, horn-shaped, describing the knobbly root, through Greek and Latin."),
        entry("pineapple", "noun",
              "A large tropical fruit with spiky skin.",
              "We carved the pineapple into a boat for the party.",
              "Pineapple first meant pine cone in English. When Europeans saw the fruit, they gave it the same name because it looked like one."),
        entry("coconut", "noun",
              "The large hard-shelled fruit of the coconut palm.",
              "It took three of us and a rock to open the coconut.",
              "From Portuguese coco, a grinning face or bogeyman: the three holes on the shell look like a face."),
        entry("bug", "noun",
              "An error in a computer program; also an insect.",
              "A bug in the app kept showing tomorrow's weather as yesterday's.",
              "Engineers called faults bugs long before computers. In 1947 Grace Hopper's team found a real moth in the Harvard Mark II computer and taped it in their log."),
        entry("spam", "noun",
              "Unwanted messages sent in bulk.",
              "My inbox is full of spam about prizes I never entered.",
              "From a 1970 Monty Python sketch in which a group of singers drowns out a cafe conversation by chanting Spam over and over."),
        entry("wiki", "noun",
              "A website that anyone can help write and edit.",
              "We made a wiki of all our family recipes.",
              "Hawaiian for quick. Programmer Ward Cunningham named his 1995 website after the Wiki Wiki Shuttle buses at Honolulu airport."),
        entry("bluetooth", "noun",
              "A way of connecting devices wirelessly over short distances.",
              "The speaker connected over Bluetooth and blasted the wrong song.",
              "Named after Harald Bluetooth, a 10th-century king who united Denmark and Norway, just as the technology unites devices."),
        entry("meme", "noun",
              "An idea, joke or image that spreads from person to person.",
              "That dancing cat meme is everywhere this week.",
              "Coined by biologist Richard Dawkins in 1976 from Greek mimema, something imitated, shortened to rhyme with gene."),
        entry("velcro", "noun",
              "A fastener made of tiny hooks and loops.",
              "Velcro shoes are the reason I never learned to tie laces.",
              "Invented by Swiss engineer George de Mestral after burrs stuck to his dog. From French velours, velvet, and crochet, hook."),
        entry("crossword", "noun",
              "A puzzle of words fitted into a grid of squares.",
              "Grandpa does the crossword in pen to show off.",
              "Invented by Arthur Wynne for a New York newspaper in 1913. He called it a word-cross."),
        entry("sudoku", "noun",
              "A number puzzle filling a grid so each row, column and box has the digits 1 to 9.",
              "She solved the sudoku before her tea went cold.",
              "Japanese, short for a phrase meaning the digits must remain single. The puzzle itself was first published in the USA in 1979."),
        entry("mascot", "noun",
              "A person, animal or object thought to bring good luck.",
              "The team's mascot is a goat called Captain.",
              "From French mascotte, from Provencal masco, witch. A popular French operetta called La Mascotte made it famous in 1880."),
        entry("trophy", "noun",
              "A cup or prize awarded for winning.",
              "The trophy was almost as tall as the captain.",
              "From Greek tropaion, a monument put up where the enemy turned and fled in battle."),
        entry("tennis", "noun",
              "A game where players hit a ball over a net with rackets.",
              "We play tennis badly but with great enthusiasm.",
              "Probably from Old French tenez, take this, called out by the server in an early version of the game."),
        entry("badminton", "noun",
              "A game played with rackets and a shuttlecock.",
              "Our garden badminton net is also the washing line.",
              "Named after Badminton House, the Duke of Beaufort's country estate in England, where the game was popular in the 1870s."),
        entry("hat-trick", "noun",
              "Three successes in a row, such as three goals or three wickets.",
              "She scored a hat-trick in the very first match of the season.",
              "From cricket: in 1858, bowler H. H. Stephenson took three wickets with three balls and was presented with a hat."),
        entry("grinch", "noun",
              "A grumpy person who spoils other people's fun.",
              "Do not be a grinch, come and dance!",
              "From the Grinch, the grumpy character in Dr Seuss's 1957 book How the Grinch Stole Christmas!"),
        entry("scrooge", "noun",
              "A mean person who hates spending money.",
              "My brother is a total scrooge with his pocket money.",
              "From Ebenezer Scrooge, the miser in Charles Dickens's A Christmas Carol (1843)."),
        entry("pollyanna", "noun",
              "A person who is always cheerful and optimistic, sometimes too much so.",
              "She is such a pollyanna that she called the flat tyre a chance to stretch our legs.",
              "From Pollyanna, the relentlessly cheerful heroine of Eleanor H. Porter's 1913 novel."),
        entry("cyberspace", "noun",
              "The online world of computer networks.",
              "My homework disappeared somewhere into cyberspace.",
              "Coined by science fiction writer William Gibson in a 1982 short story, and made famous by his novel Neuromancer."),
        entry("swagger", "verb",
              "To walk or behave in a very confident, showy way.",
              "He swaggered into class wearing his new sunglasses.",
              "First recorded in Shakespeare's A Midsummer Night's Dream, around 1590."),
        entry("dunce", "noun",
              "A person who is slow to learn.",
              "I felt like a dunce when I could not open the milk carton.",
              "From John Duns Scotus, a brilliant medieval thinker. Later scholars mocked his old-fashioned followers as Dunsmen."),
        entry("barbarian", "noun",
              "A rough, uncivilised person.",
              "Only a barbarian would eat the icing and leave the cake.",
              "From Greek barbaros, a foreigner. To Greeks, other languages sounded like bar-bar-bar."),
        entry("gossip", "noun",
              "Casual talk about other people's lives.",
              "The aunties shared the latest gossip over chai.",
              "From Old English godsibb, a godparent. Close family friends chatted at christenings, and the word drifted to mean idle talk."),
        entry("glamour", "noun",
              "Attractive, exciting charm.",
              "The film premiere was full of glamour and flashing cameras.",
              "A Scottish form of grammar, meaning magic or a spell, because learning was linked to the occult. Walter Scott popularised it."),
        entry("nice", "adjective",
              "Pleasant or kind.",
              "It was nice of you to save me a seat.",
              "From Latin nescius, ignorant. In the 1300s nice meant foolish; it took centuries to become pleasant."),
        entry("silly", "adjective",
              "Foolish in a light-hearted way.",
              "We pulled silly faces for the family photo.",
              "From Old English saelig, happy or blessed. Over time it went from blessed to innocent to foolish."),
        entry("awful", "adjective",
              "Very bad or unpleasant.",
              "The traffic this morning was awful.",
              "It first meant full of awe, inspiring wonder. Only later did it slide towards terrible."),
        entry("egregious", "adjective",
              "Shockingly bad.",
              "Putting pineapple in the biryani was an egregious mistake.",
              "From Latin ex grege, out of the flock. It once meant remarkably good, standing out from the crowd."),
        entry("jeopardy", "noun",
              "Danger of loss or harm.",
              "The picnic was in jeopardy when the clouds rolled in.",
              "From Old French jeu parti, a divided game, one where the chances are evenly split."),
        entry("quiz", "noun",
              "A test of knowledge, often as a game.",
              "Our family quiz night ended in a fierce argument about capitals.",
              "Nobody knows. A famous story about a Dublin theatre owner inventing it for a bet in 1791 is almost certainly made up."),
        entry("hazard", "noun",
              "A danger or risk.",
              "The toy cars on the stairs were a serious hazard.",
              "From Old French hasard, a game of dice, possibly from Arabic az-zahr, the die."),
        entry("jamboree", "noun",
              "A large, lively celebration or gathering.",
              "The school's end-of-year jamboree had music, games and a dunk tank.",
              "American slang from the 1860s, of unknown origin. Robert Baden-Powell chose it for the great Scout gathering of 1920."),
        entry("typhoon", "noun",
              "A violent tropical storm in the western Pacific.",
              "The typhoon kept everyone indoors for two days.",
              "Possibly from Chinese tai fung, great wind, blended with Typhon, a monster of storms in Greek myth."),
        entry("naughty", "adjective",
              "Badly behaved, usually of a child.",
              "The naughty puppy chewed one shoe from every pair.",
              "It first meant having naught, poor or needy, and later wicked, before softening to mischievous."),
    ]
}
